In [2]:
## RUN

import sys

In [3]:
## RUN

from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("Weather_Batch_Conversion") \
    .master("local[*]") \
    .config("spark.sql.shuffle.partitions","20") \
    .getOrCreate()

spark.version

'3.5.6'

In [4]:
extract_path = r"D:\Weather\Extracted"

os.makedirs(extract_path, exist_ok=True)

In [ ]:
import zipfile
import pandas as pd
import os
import time


zip_path = r"D:\Weather\archive.zip"

output_path = r"D:\Weather\parquet\w_d_1"

os.makedirs(output_path, exist_ok=True)


with zipfile.ZipFile(zip_path, 'r') as z:

    # get only w_d_1 csv files
    csv_files = [
        f for f in z.namelist()
        if f.startswith("w_d_1/")
        and f.endswith(".csv")
    ]

    print("Total w_d_1 files:", len(csv_files))


    start = time.time()


    for i, file in enumerate(csv_files):

        try:

            city = os.path.basename(file).replace(".csv", "")

            print(
                f"\n[{i+1}/{len(csv_files)}] Processing {city}"
            )


            # read csv from zip
            with z.open(file) as f:

                df = pd.read_csv(
                    f,
                    encoding="utf-8-sig"
                )


            # add city column
            df["city"] = city


            # parquet output path
            output_file = os.path.join(
                output_path,
                city + ".parquet"
            )


            # save parquet
            df.to_parquet(
                output_file,
                engine="pyarrow",
                index=False
            )


            print(
                "Saved:",
                output_file,
                "Rows:",
                len(df)
            )


        except Exception as e:

            print(
                "FAILED:",
                city,
                e
            )


    print("\nCompleted")
    print(
        "Total time:",
        round((time.time()-start)/60,2),
        "minutes"
    )

Total w_d_1 files: 1762

[1/1762] Processing Abbigeri
Saved: D:\Weather\parquet\w_d_1\Abbigeri.parquet Rows: 123936

[2/1762] Processing Abdullahnagar
Saved: D:\Weather\parquet\w_d_1\Abdullahnagar.parquet Rows: 123936

[3/1762] Processing Abhayapuri
Saved: D:\Weather\parquet\w_d_1\Abhayapuri.parquet Rows: 123936

[4/1762] Processing Abhia
Saved: D:\Weather\parquet\w_d_1\Abhia.parquet Rows: 123936

[5/1762] Processing Abhwar
Saved: D:\Weather\parquet\w_d_1\Abhwar.parquet Rows: 123936

[6/1762] Processing Abiramam
Saved: D:\Weather\parquet\w_d_1\Abiramam.parquet Rows: 123936

[7/1762] Processing Ablu
Saved: D:\Weather\parquet\w_d_1\Ablu.parquet Rows: 123936

[8/1762] Processing Abohar
Saved: D:\Weather\parquet\w_d_1\Abohar.parquet Rows: 123936

[9/1762] Processing Abu
Saved: D:\Weather\parquet\w_d_1\Abu.parquet Rows: 123936

[10/1762] Processing Achaljamu
Saved: D:\Weather\parquet\w_d_1\Achaljamu.parquet Rows: 123936

[11/1762] Processing Achampet
Saved: D:\Weather\parquet\w_d_1\Achampet.parquet Rows: 123936

[12/1762] Processing Acharipallam
Saved: D:\Weather\parquet\w_d_1\Acharipallam.parquet Rows: 123936

[13/1762] Processing Achchippatti
Saved: D:\Weather\parquet\w_d_1\Achchippatti.parquet Rows: 123936

[14/1762] Processing Achhnera
Saved: D:\Weather\parquet\w_d_1\Achhnera.parquet Rows: 123936

[15/1762] Processing Adalaj
Saved: D:\Weather\parquet\w_d_1\Adalaj.parquet Rows: 123936

[16/1762] Processing Adalpur
Saved: D:\Weather\parquet\w_d_1\Adalpur.parquet Rows: 123936

[17/1762] Processing Adamankottai
Saved: D:\Weather\parquet\w_d_1\Adamankottai.parquet Rows: 123936

[18/1762] Processing Adampur
Saved: D:\Weather\parquet\w_d_1\Adampur.parquet Rows: 123936

[19/1762] Processing Addanki
Saved: D:\Weather\parquet\w_d_1\Addanki.parquet Rows: 123936

[20/1762] Processing Adigappadi
Saved: D:\Weather\parquet\w_d_1\Adigappadi.parquet Rows: 123936

[21/1762] Processing Adigaratti
Saved: D:\Weather\parquet\w_d_1\Adigaratti.parquet Rows: 123936

[22/1762] Processing Adigoppula
Saved: D:\Weather\parquet\w_d_1\Adigoppula.parquet Rows: 123936

[23/1762] Processing Adilabad
Saved: D:\Weather\parquet\w_d_1\Adilabad.parquet Rows: 123936

[24/1762] Processing Adivala
Saved: D:\Weather\parquet\w_d_1\Adivala.parquet Rows: 123936

[25/1762] Processing Adiyakkamangalam
Saved: D:\Weather\parquet\w_d_1\Adiyakkamangalam.parquet Rows: 123936

[26/1762] Processing Adoni
Saved: D:\Weather\parquet\w_d_1\Adoni.parquet Rows: 123936

[27/1762] Processing Adra
Saved: D:\Weather\parquet\w_d_1\Adra.parquet Rows: 123936

[28/1762] Processing Advi Devalpalli
Saved: D:\Weather\parquet\w_d_1\Advi Devalpalli.parquet Rows: 123936

[29/1762] Processing Adyar
Saved: D:\Weather\parquet\w_d_1\Adyar.parquet Rows: 123936

[30/1762] Processing Afzala
Saved: D:\Weather\parquet\w_d_1\Afzala.parquet Rows: 123936

[31/1762] Processing Afzalpur
Saved: D:\Weather\parquet\w_d_1\Afzalpur.parquet Rows: 123936

[32/1762] Processing Agadallanka
Saved: D:\Weather\parquet\w_d_1\Agadallanka.parquet Rows: 123936

[33/1762] Processing Agadi
Saved: D:\Weather\parquet\w_d_1\Agadi.parquet Rows: 123936

[34/1762] Processing Agar
Saved: D:\Weather\parquet\w_d_1\Agar.parquet Rows: 123936

[35/1762] Processing Agaram
Saved: D:\Weather\parquet\w_d_1\Agaram.parquet Rows: 123936

[36/1762] Processing Agarpur
Saved: D:\Weather\parquet\w_d_1\Agarpur.parquet Rows: 123936

[37/1762] Processing Agartala
Saved: D:\Weather\parquet\w_d_1\Agartala.parquet Rows: 123936

[38/1762] Processing Aginiparru
Saved: D:\Weather\parquet\w_d_1\Aginiparru.parquet Rows: 123936

[39/1762] Processing Agiripalle
Saved: D:\Weather\parquet\w_d_1\Agiripalle.parquet Rows: 123936

[40/1762] Processing Agra
Saved: D:\Weather\parquet\w_d_1\Agra.parquet Rows: 123936

[41/1762] Processing Agwar
Saved: D:\Weather\parquet\w_d_1\Agwar.parquet Rows: 123936

[42/1762] Processing Ahirauliya
Saved: D:\Weather\parquet\w_d_1\Ahirauliya.parquet Rows: 123936

[43/1762] Processing Ahiro
Saved: D:\Weather\parquet\w_d_1\Ahiro.parquet Rows: 123936

[44/1762] Processing Ahmadabad
Saved: D:\Weather\parquet\w_d_1\Ahmadabad.parquet Rows: 123936

[45/1762] Processing Ahmadnagar
Saved: D:\Weather\parquet\w_d_1\Ahmadnagar.parquet Rows: 123936

[46/1762] Processing Ahmadpur
Saved: D:\Weather\parquet\w_d_1\Ahmadpur.parquet Rows: 123936

[47/1762] Processing Ahmedabad
Saved: D:\Weather\parquet\w_d_1\Ahmedabad.parquet Rows: 123936

[48/1762] Processing Aigali
Saved: D:\Weather\parquet\w_d_1\Aigali.parquet Rows: 123936

[49/1762] Processing Ainapur
Saved: D:\Weather\parquet\w_d_1\Ainapur.parquet Rows: 123936

[50/1762] Processing Aizawl
Saved: D:\Weather\parquet\w_d_1\Aizawl.parquet Rows: 123936

[51/1762] Processing Ajaigarh
Saved: D:\Weather\parquet\w_d_1\Ajaigarh.parquet Rows: 123936

[52/1762] Processing Ajas
Saved: D:\Weather\parquet\w_d_1\Ajas.parquet Rows: 123936

[53/1762] Processing Ajjampur
Saved: D:\Weather\parquet\w_d_1\Ajjampur.parquet Rows: 123936

[54/1762] Processing Ajjanahalli
Saved: D:\Weather\parquet\w_d_1\Ajjanahalli.parquet Rows: 123936

[55/1762] Processing Ajjipuram
Saved: D:\Weather\parquet\w_d_1\Ajjipuram.parquet Rows: 123936

[56/1762] Processing Ajmer
Saved: D:\Weather\parquet\w_d_1\Ajmer.parquet Rows: 123936

[57/1762] Processing Ajnala
Saved: D:\Weather\parquet\w_d_1\Ajnala.parquet Rows: 123936

[58/1762] Processing Ajodhya
Saved: D:\Weather\parquet\w_d_1\Ajodhya.parquet Rows: 123936

[59/1762] Processing Akalgarh
Saved: D:\Weather\parquet\w_d_1\Akalgarh.parquet Rows: 123936

[60/1762] Processing Akanavaritota
Saved: D:\Weather\parquet\w_d_1\Akanavaritota.parquet Rows: 123936

[61/1762] Processing Akbarpur
Saved: D:\Weather\parquet\w_d_1\Akbarpur.parquet Rows: 123936

[62/1762] Processing Akbarpur_2
Saved: D:\Weather\parquet\w_d_1\Akbarpur_2.parquet Rows: 123936

[63/1762] Processing Akhnur
Saved: D:\Weather\parquet\w_d_1\Akhnur.parquet Rows: 123936

[64/1762] Processing Akividu
Saved: D:\Weather\parquet\w_d_1\Akividu.parquet Rows: 123936

[65/1762] Processing Aklvidu
Saved: D:\Weather\parquet\w_d_1\Aklvidu.parquet Rows: 123936

[66/1762] Processing Akola
Saved: D:\Weather\parquet\w_d_1\Akola.parquet Rows: 123936

[67/1762] Processing Akora
Saved: D:\Weather\parquet\w_d_1\Akora.parquet Rows: 123936

[68/1762] Processing Akot
Saved: D:\Weather\parquet\w_d_1\Akot.parquet Rows: 123936

[69/1762] Processing Alagappapuram
Saved: D:\Weather\parquet\w_d_1\Alagappapuram.parquet Rows: 123936

[70/1762] Processing Alagarai
Saved: D:\Weather\parquet\w_d_1\Alagarai.parquet Rows: 123936

[71/1762] Processing Alamnagar
Saved: D:\Weather\parquet\w_d_1\Alamnagar.parquet Rows: 123936

[72/1762] Processing Alampalaiyam
Saved: D:\Weather\parquet\w_d_1\Alampalaiyam.parquet Rows: 123936

[73/1762] Processing Alampur Gonpura
Saved: D:\Weather\parquet\w_d_1\Alampur Gonpura.parquet Rows: 123936

[74/1762] Processing Alampur
Saved: D:\Weather\parquet\w_d_1\Alampur.parquet Rows: 123936

[75/1762] Processing Alampur_2
Saved: D:\Weather\parquet\w_d_1\Alampur_2.parquet Rows: 123936

[76/1762] Processing Alampur_3
Saved: D:\Weather\parquet\w_d_1\Alampur_3.parquet Rows: 123936

[77/1762] Processing Alamuru
Saved: D:\Weather\parquet\w_d_1\Alamuru.parquet Rows: 123936

[78/1762] Processing Aland
Saved: D:\Weather\parquet\w_d_1\Aland.parquet Rows: 123936

[79/1762] Processing Alanganallur
Saved: D:\Weather\parquet\w_d_1\Alanganallur.parquet Rows: 123936

[80/1762] Processing Alangayam
Saved: D:\Weather\parquet\w_d_1\Alangayam.parquet Rows: 123936

[81/1762] Processing Alangudi
Saved: D:\Weather\parquet\w_d_1\Alangudi.parquet Rows: 123936

[82/1762] Processing Alangulam
Saved: D:\Weather\parquet\w_d_1\Alangulam.parquet Rows: 123936

[83/1762] Processing Alasandigutta
Saved: D:\Weather\parquet\w_d_1\Alasandigutta.parquet Rows: 123936

[84/1762] Processing Alauli
Saved: D:\Weather\parquet\w_d_1\Alauli.parquet Rows: 123936

[85/1762] Processing Alawalpur
Saved: D:\Weather\parquet\w_d_1\Alawalpur.parquet Rows: 123936

[86/1762] Processing Alawandi
Saved: D:\Weather\parquet\w_d_1\Alawandi.parquet Rows: 123936

[87/1762] Processing Aldona
Saved: D:\Weather\parquet\w_d_1\Aldona.parquet Rows: 123936

[88/1762] Processing Algun
Saved: D:\Weather\parquet\w_d_1\Algun.parquet Rows: 123936

[89/1762] Processing Aliganj
Saved: D:\Weather\parquet\w_d_1\Aliganj.parquet Rows: 123936

[90/1762] Processing Aligarh
Saved: D:\Weather\parquet\w_d_1\Aligarh.parquet Rows: 123936

[91/1762] Processing Alipur Duar
Saved: D:\Weather\parquet\w_d_1\Alipur Duar.parquet Rows: 123936

[92/1762] Processing Alipur
Saved: D:\Weather\parquet\w_d_1\Alipur.parquet Rows: 123936

[93/1762] Processing Alipura
Saved: D:\Weather\parquet\w_d_1\Alipura.parquet Rows: 123936

[94/1762] Processing Aliyabad
Saved: D:\Weather\parquet\w_d_1\Aliyabad.parquet Rows: 123936

[95/1762] Processing Allagadda
Saved: D:\Weather\parquet\w_d_1\Allagadda.parquet Rows: 123936

[96/1762] Processing Allahdurg
Saved: D:\Weather\parquet\w_d_1\Allahdurg.parquet Rows: 123936

[97/1762] Processing Allahpur
Saved: D:\Weather\parquet\w_d_1\Allahpur.parquet Rows: 123936

[98/1762] Processing Alleppey
Saved: D:\Weather\parquet\w_d_1\Alleppey.parquet Rows: 123936

[99/1762] Processing Allinagaram
Saved: D:\Weather\parquet\w_d_1\Allinagaram.parquet Rows: 123936

[100/1762] Processing Allur
Saved: D:\Weather\parquet\w_d_1\Allur.parquet Rows: 123936

[101/1762] Processing Alluru
Saved: D:\Weather\parquet\w_d_1\Alluru.parquet Rows: 123936

[102/1762] Processing Almel
Saved: D:\Weather\parquet\w_d_1\Almel.parquet Rows: 123936

[103/1762] Processing Almora
Saved: D:\Weather\parquet\w_d_1\Almora.parquet Rows: 123936

[104/1762] Processing Alnavar

In [9]:
import zipfile
import pandas as pd
import os
import time


zip_path = r"D:\Weather\archive.zip"

output_path = r"D:\Weather\parquet\w_d_2"

os.makedirs(output_path, exist_ok=True)


with zipfile.ZipFile(zip_path, 'r') as z:

    # get only w_d_2 csv files
    csv_files = [
        f for f in z.namelist()
        if f.startswith("w_d_2/")
        and f.endswith(".csv")
    ]

    print("Total w_d_2 files:", len(csv_files))


    start = time.time()


    for i, file in enumerate(csv_files):

        try:

            city = os.path.basename(file).replace(".csv", "")

            print(
                f"\n[{i+1}/{len(csv_files)}] Processing {city}"
            )


            # read csv directly from zip
            with z.open(file) as f:

                df = pd.read_csv(
                    f,
                    encoding="utf-8-sig"
                )


            # add city column
            df["city"] = city


            # parquet file path
            output_file = os.path.join(
                output_path,
                city + ".parquet"
            )


            # convert to parquet
            df.to_parquet(
                output_file,
                engine="pyarrow",
                index=False
            )


            print(
                "Saved:",
                city,
                "Rows:",
                len(df)
            )


        except Exception as e:

            print(
                "FAILED:",
                city,
                e
            )


    print("\nW_D_2 Completed")

    print(
        "Total time:",
        round((time.time()-start)/60,2),
        "minutes"
    )

Total w_d_2 files: 2087

[1/2087] Processing Habra
Saved: Habra Rows: 123936

[2/2087] Processing Hadagalli
Saved: Hadagalli Rows: 123936

[3/2087] Processing Hadiaya
Saved: Hadiaya Rows: 123936

[4/2087] Processing Hagaribommanahalli
Saved: Hagaribommanahalli Rows: 123936

[5/2087] Processing Haidarnagar
Saved: Haidarnagar Rows: 123936

[6/2087] Processing Hailakandi
Saved: Hailakandi Rows: 123936

[7/2087] Processing Hajan
Saved: Hajan Rows: 123936

[8/2087] Processing Hajipur
Saved: Hajipur Rows: 123936

[9/2087] Processing Hajipur_2
Saved: Hajipur_2 Rows: 123936

[10/2087] Processing Hajipur_3
Saved: Hajipur_3 Rows: 123936

[11/2087] Processing Hakka
Saved: Hakka Rows: 123936

[12/2087] Processing Halavagalu
Saved: Halavagalu Rows: 123936

[13/2087] Processing Haldia
Saved: Haldia Rows: 123936

[14/2087] Processing Haldibari
Saved: Haldibari Rows: 123936

[15/2087] Processing Haldipur
Saved: Haldipur Rows: 123936

[16/2087] Processing Hale Dyamavvanahalli
Saved: Hale Dyamavvanahalli Rows: 123936

[17/2087] Processing Halge
Saved: Halge Rows: 123936

[18/2087] Processing Halgeri
Saved: Halgeri Rows: 123936

[19/2087] Processing Halgur
Saved: Halgur Rows: 123936

[20/2087] Processing Halisahar
Saved: Halisahar Rows: 123936

[21/2087] Processing Haliyal
Saved: Haliyal Rows: 123936

[22/2087] Processing Halsur
Saved: Halsur Rows: 123936

[23/2087] Processing Halwara
Saved: Halwara Rows: 123936

[24/2087] Processing Hamira
Saved: Hamira Rows: 123936

[25/2087] Processing Hamsavaram
Saved: Hamsavaram Rows: 123936

[26/2087] Processing Hanamsagar
Saved: Hanamsagar Rows: 123936

[27/2087] Processing Handwara
Saved: Handwara Rows: 123936

[28/2087] Processing Hangal
Saved: Hangal Rows: 123936

[29/2087] Processing Hansa
Saved: Hansa Rows: 123936

[30/2087] Processing Hansi
Saved: Hansi Rows: 123936

[31/2087] Processing Hanumana
Saved: Hanumana Rows: 123936

[32/2087] Processing Hanumangarh
Saved: Hanumangarh Rows: 123936

[33/2087] Processing Hanumantanpatti
Saved: Hanumantanpatti Rows: 123936

[34/2087] Processing Hanur
Saved: Hanur Rows: 123936

[35/2087] Processing Hanzviur
Saved: Hanzviur Rows: 123936

[36/2087] Processing Haora
Saved: Haora Rows: 123936

[37/2087] Processing Hapur
Saved: Hapur Rows: 123936

[38/2087] Processing Harbatpur
Saved: Harbatpur Rows: 123936

[39/2087] Processing Harda Khas
Saved: Harda Khas Rows: 123936

[40/2087] Processing Hardas Bigha
Saved: Hardas Bigha Rows: 123936

[41/2087] Processing Hardi
Saved: Hardi Rows: 123936

[42/2087] Processing Hardia
Saved: Hardia Rows: 123936

[43/2087] Processing Hardia_2
Saved: Hardia_2 Rows: 123936

[44/2087] Processing Hardiya
Saved: Hardiya Rows: 123936

[45/2087] Processing Hardiya_2
Saved: Hardiya_2 Rows: 123936

[46/2087] Processing Harduli
Saved: Harduli Rows: 123936

[47/2087] Processing Harewa
Saved: Harewa Rows: 123936

[48/2087] Processing Hargawan
Saved: Hargawan Rows: 123936

[49/2087] Processing Hariana
Saved: Hariana Rows: 123936

[50/2087] Processing Haridwar
Saved: Haridwar Rows: 123936

[51/2087] Processing Harihans
Saved: Harihans Rows: 123936

[52/2087] Processing Harihar
Saved: Harihar Rows: 123936

[53/2087] Processing Hariharpara
Saved: Hariharpara Rows: 123936

[54/2087] Processing Harike
Saved: Harike Rows: 123936

[55/2087] Processing Haripur
Saved: Haripur Rows: 123936

[56/2087] Processing Haripur_2
Saved: Haripur_2 Rows: 123936

[57/2087] Processing Haripura
Saved: Haripura Rows: 123936

[58/2087] Processing Harlakhi
Saved: Harlakhi Rows: 123936

[59/2087] Processing Harohalli
Saved: Harohalli Rows: 123936

[60/2087] Processing Harohalli_2
Saved: Harohalli_2 Rows: 123936

[61/2087] Processing Harpalpur
Saved: Harpalpur Rows: 123936

[62/2087] Processing Harpanahalli
Saved: Harpanahalli Rows: 123936

[63/2087] Processing Harpur Bhindi
Saved: Harpur Bhindi Rows: 123936

[64/2087] Processing Harpur Bochaha
Saved: Harpur Bochaha Rows: 123936

[65/2087] Processing Harpur Pusa
Saved: Harpur Pusa Rows: 123936

[66/2087] Processing Harpur
Saved: Harpur Rows: 123936

[67/2087] Processing Harpur_2
Saved: Harpur_2 Rows: 123936

[68/2087] Processing Harrai
Saved: Harrai Rows: 123936

[69/2087] Processing Harri
Saved: Harri Rows: 123936

[70/2087] Processing Harsinghpur
Saved: Harsinghpur Rows: 123936

[71/2087] Processing Harsola
Saved: Harsola Rows: 123936

[72/2087] Processing Harua
Saved: Harua Rows: 123936

[73/2087] Processing Harur
Saved: Harur Rows: 123936

[74/2087] Processing Hasanparti
Saved: Hasanparti Rows: 123936

[75/2087] Processing Hasanpur Juned
Saved: Hasanpur Juned Rows: 123936

[76/2087] Processing Hasanpur
Saved: Hasanpur Rows: 123936

[77/2087] Processing Hasanpur_2
Saved: Hasanpur_2 Rows: 123936

[78/2087] Processing Hasanpura
Saved: Hasanpura Rows: 123936

[79/2087] Processing Hassan
Saved: Hassan Rows: 123936

[80/2087] Processing Hata
Saved: Hata Rows: 123936

[81/2087] Processing Hathapur
Saved: Hathapur Rows: 123936

[82/2087] Processing Hathaura
Saved: Hathaura Rows: 123936

[83/2087] Processing Hathauri
Saved: Hathauri Rows: 123936

[84/2087] Processing Hathiakan
Saved: Hathiakan Rows: 123936

[85/2087] Processing Hathiaundha
Saved: Hathiaundha Rows: 123936

[86/2087] Processing Hathidah Buzurg
Saved: Hathidah Buzurg Rows: 123936

[87/2087] Processing Hathras
Saved: Hathras Rows: 123936

[88/2087] Processing Hathwan
Saved: Hathwan Rows: 123936

[89/2087] Processing Hatod
Saved: Hatod Rows: 123936

[90/2087] Processing Hatta
Saved: Hatta Rows: 123936

[91/2087] Processing Hatti Mattur
Saved: Hatti Mattur Rows: 123936

[92/2087] Processing Hatti
Saved: Hatti Rows: 123936

[93/2087] Processing Hatwans
Saved: Hatwans Rows: 123936

[94/2087] Processing Havanur
Saved: Havanur Rows: 123936

[95/2087] Processing Haveri
Saved: Haveri Rows: 123936

[96/2087] Processing Havi Bhauar
Saved: Havi Bhauar Rows: 123936

[97/2087] Processing Hazaribagh
Saved: Hazaribagh Rows: 123936

[98/2087] Processing Hazrat Shiura
Saved: Hazrat Shiura Rows: 123936

[99/2087] Processing Hebli
Saved: Hebli Rows: 123936

[100/2087] Processing Hegde
Saved: Hegde Rows: 123936

[101/2087] Processing Heggadadevankote
Saved: Heggadadevankote Rows: 123936

[102/2087] Processing Hejamadi
Saved: Hejamadi Rows: 123936

[103/2087] Processing Hemavati
Saved: Hemavati Rows: 123936

[104/2087] Processing Herohalli
Saved: Herohalli Rows: 123936

[105/2087] Processing Herseh Chhina
Saved: Herseh Chhina Rows: 123936

[106/2087] Processing Hesarghatta
Saved: Hesarghatta Rows: 123936

[107/2087] Processing Hetanpur
Saved: Hetanpur Rows: 123936

[108/2087] Processing Hilsa
Saved: Hilsa Rows: 123936

[109/2087] Processing Himatnagar
Saved: Himatnagar Rows: 123936

[110/2087] Processing Himmatpura
Saved: Himmatpura Rows: 123936

[111/2087] Processing Hindalgi
Saved: Hindalgi Rows: 123936

[112/2087] Processing Hindoria
Saved: Hindoria Rows: 123936

[113/2087] Processing Hindupur
Saved: Hindupur Rows: 123936

[114/2087] Processing Hipparga
Saved: Hipparga Rows: 123936

[115/2087] Processing Hirakud
Saved: Hirakud Rows: 123936

[116/2087] Processing Hiramandalam
Saved: Hiramandalam Rows: 123936

[117/2087] Processing Hire Megalageri
Saved: Hire Megalageri Rows: 123936

[118/2087] Processing Hire Vadvatti
Saved: Hire Vadvatti Rows: 123936

[119/2087] Processing Hirehadagalli
Saved: Hirehadagalli Rows: 123936

[120/2087] Processing Hirehalli
Saved: Hirehalli Rows: 123936

[121/2087] Processing Hirehaluhosahalli
Saved: Hirehaluhosahalli Rows: 123936

[122/2087] Processing Hirekerur
Saved: Hirekerur Rows: 123936

[123/2087] Processing Hiriyur
Saved: Hiriyur Rows: 123936

[124/2087] Processing Hirni
Saved: Hirni Rows: 123936

[125/2087] Processing Hirpardangal
Saved: Hirpardangal Rows: 123936

[126/2087] Processing Hisar
Saved: Hisar Rows: 123936

[127/2087] Processing Hisar_2
Saved: Hisar_2 Rows: 123936

[128/2087] Processing Hissaramuruvani
Saved: Hissaramuruvani Rows: 123936

[129/2087] Processing Hisua
Saved: Hisua Rows: 123936

[130/2087] Processing Hojai
Saved: Hojai Rows: 123936

[131/2087] Processing Holagondi
Saved: Holagondi Rows: 123936

[132/2087] Processing Holalagondi
Saved: Holalagondi Rows: 123936

[133/2087] Processing Holalkere
Saved: Holalkere Rows: 123936

[134/2087] Processing Holalu
Saved: Holalu Rows: 123936

[135/2087] Processing Hole Narsipur
Saved: Hole Narsipur Rows: 123936

[136/2087] Processing Hombal
Saved: Hombal Rows: 123936

[137/2087] Processing Homnabad
Saved: Homnabad Rows: 123936

[138/2087] Processing Honavar
Saved: Honavar Rows: 123936

[139/2087] Processing Honganur
Saved: Honganur Rows: 123936

[140/2087] Processing Honganur_2
Saved: Honganur_2 Rows: 123936

[141/2087] Processing Honge
Saved: Honge Rows: 123936

[142/2087] Processing Honnali
Saved: Honnali Rows: 123936

[143/2087] Processing Honwad
Saved: Honwad Rows: 123936

[144/2087] Processing Honwada
Saved: Honwada Rows: 123936

[145/2087] Processing Honwada_2
Saved: Honwada_2 Rows: 123936

[146/2087] Processing Horti
Saved: Horti Rows: 123936

[147/2087] Processing Hosahalli
Saved: Hosahalli Rows: 123936

[148/2087] Processing Hosahalli_2
Saved: Hosahalli_2 Rows: 123936

[149/2087] Processing Hosakote
Saved: Hosakote Rows: 123936

[150/2087] Processing Hosdurga
Saved: Hosdurga Rows: 123936

[151/2087] Processing Hoshangabad
Saved: Hoshangabad Rows: 123936

[152/2087] Processing Hosir
Saved: Hosir Rows: 123936

[153/2087] Processing Hoskote
Saved: Hoskote Rows: 123936

[154/2087] Processing Hospet
Saved: Hospet Rows: 123936

[155/2087] Processing Hosur
Saved: Hosur Rows: 123936

[156/2087] Processing Hosur_2
Saved: Hosur_2 Rows: 123936

[157/2087] Processing Hosuru
Saved: Hosuru Rows: 123936

[158/2087] Processing Hosuru_2
Saved: Hosuru_2 Rows: 123936

[159/2087] Processing Howli
Saved: Howli Rows: 123936

[160/2087] Processing Hubli
Saved: Hubli Rows: 123936

[161/2087] Processing Hudem
Saved: Hudem Rows: 123936

[162/2087] Processing Hugli
Saved: Hugli Rows: 123936

[163/2087] Processing Hukeri
Saved: Hukeri Rows: 123936

[164/2087] Processing Hulgur
Saved: Hulgur Rows: 123936

[165/2087] Processing Hulikal
Saved: Hulikal Rows: 123936

[166/2087] Processing Huliyar
Saved: Huliyar Rows: 123936

[167/2087] Processing Hulkoti
Saved: Hulkoti Rows: 123936

[168/2087] Processing Hullahalli
Saved: Hullahalli Rows: 123936

[169/2087] Processing Hullatti
Saved: Hullatti Rows: 123936

[170/2087] Processing Hunasagi
Saved: Hunasagi Rows: 123936

[171/2087] Processing Hunasamaranhalli
Saved: Hunasamaranhalli Rows: 123936

[172/2087] Processing Hungund
Saved: Hungund Rows: 123936

[173/2087] Processing Hunsur
Saved: Hunsur Rows: 123936

[174/2087] Processing Husainabad
Saved: Husainabad Rows: 123936

[175/2087] Processing Husainpur
Saved: Husainpur Rows: 123936

[176/2087] Processing Huseni
Saved: Huseni Rows: 123936

[177/2087] Processing Husepur
Saved: Husepur Rows: 123936

[178/2087] Processing Husnabad
Saved: Husnabad Rows: 123936

[179/2087] Processing Hussepur
Saved: Hussepur Rows: 123936

[180/2087] Processing Huzurabad
Saved: Huzurabad Rows: 123936

[181/2087] Processing Huzurnagar
Saved: Huzurnagar Rows: 123936

[182/2087] Processing Hyderabad
Saved: Hyderabad Rows: 123936

[183/2087] Processing Iarpur
Saved: Iarpur Rows: 123936

[184/2087] Processing Iawar
Saved: Iawar Rows: 123936

[185/2087] Processing Ibrahimpatan
Saved: Ibrahimpatan Rows: 123936

[186/2087] Processing Ibrahimpatnam
Saved: Ibrahimpatnam Rows: 123936

[187/2087] Processing Ichalkaranji
Saved: Ichalkaranji Rows: 123936

[188/2087] Processing Ichchapuram
Saved: Ichchapuram Rows: 123936

[189/2087] Processing Ichhapur
Saved: Ichhapur Rows: 123936

[190/2087] Processing Ichhawar
Saved: Ichhawar Rows: 123936

[191/2087] Processing Ichora
Saved: Ichora Rows: 123936

[192/2087] Processing Idangansalai
Saved: Idangansalai Rows: 123936

[193/2087] Processing Idappadi
Saved: Idappadi Rows: 123936

[194/2087] Processing Idumbavanam
Saved: Idumbavanam Rows: 123936

[195/2087] Processing Idupugallu
Saved: Idupugallu Rows: 123936

[196/2087] Processing Ijra
Saved: Ijra Rows: 123936

[197/2087] Processing Ikhlaspur
Saved: Ikhlaspur Rows: 123936

[198/2087] Processing Ikkadu
Saved: Ikkadu Rows: 123936

[199/2087] Processing Ikkarai Boluvampatti
Saved: Ikkarai Boluvampatti Rows: 123936

[200/2087] Processing Iklod
Saved: Iklod Rows: 123936

[201/2087] Processing Ilaiyankudi
Saved: Ilaiyankudi Rows: 123936

[202/2087] Processing Ilami
Saved: Ilami Rows: 123936

[203/2087] Processing Ilampillai
Saved: Ilampillai Rows: 123936

[204/2087] Processing Ilkal
Saved: Ilkal Rows: 123936

[205/2087] Processing Iluppur
Saved: Iluppur Rows: 123936

[206/2087] Processing Imani
Saved: Imani Rows: 123936

[207/2087] Processing Imphal
Saved: Imphal Rows: 123936

[208/2087] Processing Indalvai
Saved: Indalvai Rows: 123936

[209/2087] Processing Indargarh
Saved: Indargarh Rows: 123936

[210/2087] Processing Indi
Saved: Indi Rows: 123936

[211/2087] Processing Indore
Saved: Indore Rows: 123936

[212/2087] Processing Indurti
Saved: Indurti Rows: 123936

[213/2087] Processing Indurti_2
Saved: Indurti_2 Rows: 123936

[214/2087] Processing Ingleshwar
Saved: Ingleshwar Rows: 123936

[215/2087] Processing Ingraj Bazar
Saved: Ingraj Bazar Rows: 123936

[216/2087] Processing Ingurti
Saved: Ingurti Rows: 123936

[217/2087] Processing Inkollu
Saved: Inkollu Rows: 123936

[218/2087] Processing Inole
Saved: Inole Rows: 123936

[219/2087] Processing Inungur
Saved: Inungur Rows: 123936

[220/2087] Processing Ippagudem
Saved: Ippagudem Rows: 123936

[221/2087] Processing Iraiyur
Saved: Iraiyur Rows: 123936

[222/2087] Processing Irinjalakuda
Saved: Irinjalakuda Rows: 123936

[223/2087] Processing Irugur
Saved: Irugur Rows: 123936

[224/2087] Processing Irungalur
Saved: Irungalur Rows: 123936

[225/2087] Processing Isagarh
Saved: Isagarh Rows: 123936

[226/2087] Processing Isapur
Saved: Isapur Rows: 123936

[227/2087] Processing Iskapalem
Saved: Iskapalem Rows: 123936

[228/2087] Processing Iskapalli
Saved: Iskapalli Rows: 123936

[229/2087] Processing Islamabad
Saved: Islamabad Rows: 123936

[230/2087] Processing Islampur
Saved: Islampur Rows: 123936

[231/2087] Processing Islampur_2
Saved: Islampur_2 Rows: 123936

[232/2087] Processing Islampur_3
Saved: Islampur_3 Rows: 123936

[233/2087] Processing Ismailpur
Saved: Ismailpur Rows: 123936

[234/2087] Processing Isnapuram
Saved: Isnapuram Rows: 123936

[235/2087] Processing Israin Kalan
Saved: Israin Kalan Rows: 123936

[236/2087] Processing Isua
Saved: Isua Rows: 123936

[237/2087] Processing Itahri
Saved: Itahri Rows: 123936

[238/2087] Processing Itamati
Saved: Itamati Rows: 123936

[239/2087] Processing Itamukkala
Saved: Itamukkala Rows: 123936

[240/2087] Processing Itanagar
Saved: Itanagar Rows: 123936

[241/2087] Processing Itarhi
Saved: Itarhi Rows: 123936

[242/2087] Processing Itarsi
Saved: Itarsi Rows: 123936

[243/2087] Processing Itikalapalle
Saved: Itikalapalle Rows: 123936

[244/2087] Processing Itiki
Saved: Itiki Rows: 123936

[245/2087] Processing Itki Thakurgaon
Saved: Itki Thakurgaon Rows: 123936

[246/2087] Processing Ittikelakunta
Saved: Ittikelakunta Rows: 123936

[247/2087] Processing Jabalpur
Saved: Jabalpur Rows: 123936

[248/2087] Processing Jabera
Saved: Jabera Rows: 123936

[249/2087] Processing Jadayampalaiyam
Saved: Jadayampalaiyam Rows: 123936

[250/2087] Processing Jadcherla
Saved: Jadcherla Rows: 123936

[251/2087] Processing Jadia
Saved: Jadia Rows: 123936

[252/2087] Processing Jadopur Shukul
Saved: Jadopur Shukul Rows: 123936

[253/2087] Processing Jadupatti
Saved: Jadupatti Rows: 123936

[254/2087] Processing Jagalur
Saved: Jagalur Rows: 123936

[255/2087] Processing Jagannadapuram
Saved: Jagannadapuram Rows: 123936

[256/2087] Processing Jagannathpur
Saved: Jagannathpur Rows: 123936

[257/2087] Processing Jagannathpur_2
Saved: Jagannathpur_2 Rows: 123936

[258/2087] Processing Jagatpur
Saved: Jagatpur Rows: 123936

[259/2087] Processing Jagdishpur
Saved: Jagdishpur Rows: 123936

[260/2087] Processing Jagdispur
Saved: Jagdispur Rows: 123936

[261/2087] Processing Jagdispur_2
Saved: Jagdispur_2 Rows: 123936

[262/2087] Processing Jaggampeta
Saved: Jaggampeta Rows: 123936

[263/2087] Processing Jaggayyapeta
Saved: Jaggayyapeta Rows: 123936

[264/2087] Processing Jaggisettigudem
Saved: Jaggisettigudem Rows: 123936

[265/2087] Processing Jagraon
Saved: Jagraon Rows: 123936

[266/2087] Processing Jagta
Saved: Jagta Rows: 123936

[267/2087] Processing Jahangirpur Salkhani
Saved: Jahangirpur Salkhani Rows: 123936

[268/2087] Processing Jainagar
Saved: Jainagar Rows: 123936

[269/2087] Processing Jaipur Chuhar
Saved: Jaipur Chuhar Rows: 123936

[270/2087] Processing Jaipur
Saved: Jaipur Rows: 123936

[271/2087] Processing Jaipur_2
Saved: Jaipur_2 Rows: 123936

[272/2087] Processing Jaisalmer
Saved: Jaisalmer Rows: 123936

[273/2087] Processing Jaisinghnagar
Saved: Jaisinghnagar Rows: 123936

[274/2087] Processing Jaisinghnagar_2
Saved: Jaisinghnagar_2 Rows: 123936

[275/2087] Processing Jaisinghpur
Saved: Jaisinghpur Rows: 123936

[276/2087] Processing Jaito
Saved: Jaito Rows: 123936

[277/2087] Processing Jaitpur
Saved: Jaitpur Rows: 123936

[278/2087] Processing Jaitwar
Saved: Jaitwar Rows: 123936

[279/2087] Processing Jajireddigudem
Saved: Jajireddigudem Rows: 123936

[280/2087] Processing Jajpur
Saved: Jajpur Rows: 123936

[281/2087] Processing Jakkampalaiyam
Saved: Jakkampalaiyam Rows: 123936

[282/2087] Processing Jaladurgam
Saved: Jaladurgam Rows: 123936

[283/2087] Processing Jalakandapuram
Saved: Jalakandapuram Rows: 123936

[284/2087] Processing Jalalpur
Saved: Jalalpur Rows: 123936

[285/2087] Processing Jalandhar Cantonment
Saved: Jalandhar Cantonment Rows: 123936

[286/2087] Processing Jalandhar
Saved: Jalandhar Rows: 123936

[287/2087] Processing Jalarpet
Saved: Jalarpet Rows: 123936

[288/2087] Processing Jale
Saved: Jale Rows: 123936

[289/2087] Processing Jalgaon
Saved: Jalgaon Rows: 123936

[290/2087] Processing Jalhalli
Saved: Jalhalli Rows: 123936

[291/2087] Processing Jalihalli
Saved: Jalihalli Rows: 123936

[292/2087] Processing Jalkaura
Saved: Jalkaura Rows: 123936

[293/2087] Processing Jalna
Saved: Jalna Rows: 123936

[294/2087] Processing Jalor
Saved: Jalor Rows: 123936

[295/2087] Processing Jalpaiguri
Saved: Jalpaiguri Rows: 123936

[296/2087] Processing Jalpura
Saved: Jalpura Rows: 123936

[297/2087] Processing Jamai
Saved: Jamai Rows: 123936

[298/2087] Processing Jamalpur
Saved: Jamalpur Rows: 123936

[299/2087] Processing Jamalpur_2
Saved: Jamalpur_2 Rows: 123936

[300/2087] Processing Jamalpur_3
Saved: Jamalpur_3 Rows: 123936

[301/2087] Processing Jambai
Saved: Jambai Rows: 123936

[302/2087] Processing Jambukuttaippatti
Saved: Jambukuttaippatti Rows: 123936

[303/2087] Processing Jamhor
Saved: Jamhor Rows: 123936

[304/2087] Processing Jamhra
Saved: Jamhra Rows: 123936

[305/2087] Processing Jami
Saved: Jami Rows: 123936

[306/2087] Processing Jamikunta
Saved: Jamikunta Rows: 123936

[307/2087] Processing Jamira
Saved: Jamira Rows: 123936

[308/2087] Processing Jammalamadugu
Saved: Jammalamadugu Rows: 123936

[309/2087] Processing Jammu
Saved: Jammu Rows: 123936

[310/2087] Processing Jamnagar
Saved: Jamnagar Rows: 123936

[311/2087] Processing Jamsaut
Saved: Jamsaut Rows: 123936

[312/2087] Processing Jamshedpur
Saved: Jamshedpur Rows: 123936

[313/2087] Processing Jamsher
Saved: Jamsher Rows: 123936

[314/2087] Processing Jamtara
Saved: Jamtara Rows: 123936

[315/2087] Processing Jamui
Saved: Jamui Rows: 123936

[316/2087] Processing Jamunamukh
Saved: Jamunamukh Rows: 123936

[317/2087] Processing Jamunia
Saved: Jamunia Rows: 123936

[318/2087] Processing Janai
Saved: Janai Rows: 123936

[319/2087] Processing Janakammapeta
Saved: Janakammapeta Rows: 123936

[320/2087] Processing Janapadu
Saved: Janapadu Rows: 123936

[321/2087] Processing Janapul
Saved: Janapul Rows: 123936

[322/2087] Processing Jandiala
Saved: Jandiala Rows: 123936

[323/2087] Processing Jangalapalle
Saved: Jangalapalle Rows: 123936


In [11]:
import zipfile
import pandas as pd
import os
import time


zip_path = r"D:\Weather\archive.zip"

output_path = r"D:\Weather\parquet\w_d_3"

os.makedirs(output_path, exist_ok=True)


with zipfile.ZipFile(zip_path, 'r') as z:

    # get only w_d_3 csv files
    csv_files = [
        f for f in z.namelist()
        if f.startswith("w_d_3/")
        and f.endswith(".csv")
    ]

    print("Total w_d_3 files:", len(csv_files))


    start = time.time()


    for i, file in enumerate(csv_files):

        try:

            city = os.path.basename(file).replace(".csv", "")

            print(
                f"\n[{i+1}/{len(csv_files)}] Processing {city}"
            )


            # Read CSV directly from ZIP
            with z.open(file) as f:

                df = pd.read_csv(
                    f,
                    encoding="utf-8-sig"
                )


            # Add city column
            df["city"] = city


            # Parquet output
            output_file = os.path.join(
                output_path,
                city + ".parquet"
            )


            df.to_parquet(
                output_file,
                engine="pyarrow",
                index=False
            )


            print(
                "Saved:",
                city,
                "Rows:",
                len(df)
            )


        except Exception as e:

            print(
                "FAILED:",
                city,
                e
            )


    print("\nW_D_3 Completed")

    print(
        "Total time:",
        round((time.time()-start)/60,2),
        "minutes"
    )

Total w_d_3 files: 836

[1/836] Processing Obra
Saved: Obra Rows: 123936

[2/836] Processing Obra_2
Saved: Obra_2 Rows: 123936

[3/836] Processing Odaipatti
Saved: Odaipatti Rows: 123936

[4/836] Processing Odaiyakulam
Saved: Odaiyakulam Rows: 123936

[5/836] Processing Odatturai
Saved: Odatturai Rows: 123936

[6/836] Processing Odayarpatti
Saved: Odayarpatti Rows: 123936

[7/836] Processing Odlabari
Saved: Odlabari Rows: 123936

[8/836] Processing Odugattur
Saved: Odugattur Rows: 123936

[9/836] Processing Okhargara
Saved: Okhargara Rows: 123936

[10/836] Processing Olagadam
Saved: Olagadam Rows: 123936

[11/836] Processing Olaippatti
Saved: Olaippatti Rows: 123936

[12/836] Processing Olhanpur
Saved: Olhanpur Rows: 123936

[13/836] Processing Omalur
Saved: Omalur Rows: 123936

[14/836] Processing Ommangi
Saved: Ommangi Rows: 123936

[15/836] Processing Onda
Saved: Onda Rows: 123936

[16/836] Processing Ongole
Saved: Ongole Rows: 123936

[17/836] Processing Ootacamund
Saved: Ootacamund Rows: 123936

[18/836] Processing Op
Saved: Op Rows: 123936

[19/836] Processing Oppatavadi
Saved: Oppatavadi Rows: 123936

[20/836] Processing Oppicherla
Saved: Oppicherla Rows: 123936

[21/836] Processing Orai
Saved: Orai Rows: 123936

[22/836] Processing Orchha
Saved: Orchha Rows: 123936

[23/836] Processing Osmanabad
Saved: Osmanabad Rows: 123936

[24/836] Processing Ottaikkalmantapam
Saved: Ottaikkalmantapam Rows: 123936

[25/836] Processing Ottakkadai
Saved: Ottakkadai Rows: 123936

[26/836] Processing Ottappalam
Saved: Ottappalam Rows: 123936

[27/836] Processing Ottapparai
Saved: Ottapparai Rows: 123936

[28/836] Processing Ottappidaram
Saved: Ottappidaram Rows: 123936

[29/836] Processing Oulgaret
Saved: Oulgaret Rows: 123936

[30/836] Processing Owk
Saved: Owk Rows: 123936

[31/836] Processing Pachahi
Saved: Pachahi Rows: 123936

[32/836] Processing Pachauth
Saved: Pachauth Rows: 123936

[33/836] Processing Pachchaimalaiyankottai
Saved: Pachchaimalaiyankottai Rows: 123936

[34/836] Processing Pachchampalaiyam
Saved: Pachchampalaiyam Rows: 123936

[35/836] Processing Pachhapur
Saved: Pachhapur Rows: 123936

[36/836] Processing Pachmir
Saved: Pachmir Rows: 123936

[37/836] Processing Pachor
Saved: Pachor Rows: 123936

[38/836] Processing Pachora
Saved: Pachora Rows: 123936

[39/836] Processing Pachrukha
Saved: Pachrukha Rows: 123936

[40/836] Processing Pachrukhi
Saved: Pachrukhi Rows: 123936

[41/836] Processing Padaivedu
Saved: Padaivedu Rows: 123936

[42/836] Processing Padakanti
Saved: Padakanti Rows: 123936

[43/836] Processing Padarti
Saved: Padarti Rows: 123936

[44/836] Processing Padavedu
Saved: Padavedu Rows: 123936

[45/836] Processing Padiala
Saved: Padiala Rows: 123936

[46/836] Processing Padiyanallur
Saved: Padiyanallur Rows: 123936

[47/836] Processing Padiyur
Saved: Padiyur Rows: 123936

[48/836] Processing Padmanabhapuram
Saved: Padmanabhapuram Rows: 123936

[49/836] Processing Padmapuram
Saved: Padmapuram Rows: 123936

[50/836] Processing Padra
Saved: Padra Rows: 123936

[51/836] Processing Padrauna
Saved: Padrauna Rows: 123936

[52/836] Processing Padugaipattu
Saved: Padugaipattu Rows: 123936

[53/836] Processing Padugupadu
Saved: Padugupadu Rows: 123936

[54/836] Processing Paduma
Saved: Paduma Rows: 123936

[55/836] Processing Pagidyala
Saved: Pagidyala Rows: 123936

[56/836] Processing Paharpur
Saved: Paharpur Rows: 123936

[57/836] Processing Paharpur_2
Saved: Paharpur_2 Rows: 123936

[58/836] Processing Pahsara
Saved: Pahsara Rows: 123936

[59/836] Processing Pai Bigha
Saved: Pai Bigha Rows: 123936

[60/836] Processing Paidiipalli
Saved: Paidiipalli Rows: 123936

[61/836] Processing Paiganapalli
Saved: Paiganapalli Rows: 123936

[62/836] Processing Paiker
Saved: Paiker Rows: 123936

[63/836] Processing Paikpar
Saved: Paikpar Rows: 123936

[64/836] Processing Paikpara
Saved: Paikpara Rows: 123936

[65/836] Processing Paina
Saved: Paina Rows: 123936

[66/836] Processing Painal
Saved: Painal Rows: 123936

[67/836] Processing Paithan Kawai
Saved: Paithan Kawai Rows: 123936

[68/836] Processing Paithan
Saved: Paithan Rows: 123936

[69/836] Processing Paittur
Saved: Paittur Rows: 123936

[70/836] Processing Pakala
Saved: Pakala Rows: 123936

[71/836] Processing Pakala_2
Saved: Pakala_2 Rows: 123936

[72/836] Processing Pakarya Harsidhi
Saved: Pakarya Harsidhi Rows: 123936

[73/836] Processing Pakaur
Saved: Pakaur Rows: 123936

[74/836] Processing Pakka Kalan
Saved: Pakka Kalan Rows: 123936

[75/836] Processing Pakkam
Saved: Pakkam Rows: 123936

[76/836] Processing Pakra
Saved: Pakra Rows: 123936

[77/836] Processing Pakri
Saved: Pakri Rows: 123936

[78/836] Processing Pakribarawan
Saved: Pakribarawan Rows: 123936

[79/836] Processing Palaiya Ayakkudi
Saved: Palaiya Ayakkudi Rows: 123936

[80/836] Processing Palaiyam
Saved: Palaiyam Rows: 123936

[81/836] Processing Palaiyampatti
Saved: Palaiyampatti Rows: 123936

[82/836] Processing Palakodu
Saved: Palakodu Rows: 123936

[83/836] Processing Palakollu
Saved: Palakollu Rows: 123936

[84/836] Processing Palamedu
Saved: Palamedu Rows: 123936

[85/836] Processing Palampur
Saved: Palampur Rows: 123936

[86/836] Processing Palangarai
Saved: Palangarai Rows: 123936

[87/836] Processing Palangavangudi
Saved: Palangavangudi Rows: 123936

[88/836] Processing Palangotu Adwar
Saved: Palangotu Adwar Rows: 123936

[89/836] Processing Palanisettipatti
Saved: Palanisettipatti Rows: 123936

[90/836] Processing Palankottai
Saved: Palankottai Rows: 123936

[91/836] Processing Palashi
Saved: Palashi Rows: 123936

[92/836] Processing Palavur
Saved: Palavur Rows: 123936

[93/836] Processing Palda
Saved: Palda Rows: 123936

[94/836] Processing Palepalli
Saved: Palepalli Rows: 123936

[95/836] Processing Palera
Saved: Palera Rows: 123936

[96/836] Processing Palghar
Saved: Palghar Rows: 123936

[97/836] Processing Palghat
Saved: Palghat Rows: 123936

[98/836] Processing Palhalan
Saved: Palhalan Rows: 123936

[99/836] Processing Pali
Saved: Pali Rows: 123936

[100/836] Processing Pali_2
Saved: Pali_2 Rows: 123936

[101/836] Processing Pali_3
Saved: Pali_3 Rows: 123936

[102/836] Processing Palia Kalan
Saved: Palia Kalan Rows: 123936

[103/836] Processing Palitana
Saved: Palitana Rows: 123936

[104/836] Processing Palkonda
Saved: Palkonda Rows: 123936

[105/836] Processing Palkot
Saved: Palkot Rows: 123936

[106/836] Processing Palkur
Saved: Palkur Rows: 123936

[107/836] Processing Palladam
Saved: Palladam Rows: 123936

[108/836] Processing Pallapatti
Saved: Pallapatti Rows: 123936

[109/836] Processing Pallappalaiyam
Saved: Pallappalaiyam Rows: 123936

[110/836] Processing Pallappalaiyam_2
Saved: Pallappalaiyam_2 Rows: 123936

[111/836] Processing Pallappatti
Saved: Pallappatti Rows: 123936

[112/836] Processing Pallappatti_2
Saved: Pallappatti_2 Rows: 123936

[113/836] Processing Pallattur
Saved: Pallattur Rows: 123936

[114/836] Processing Pallavaram
Saved: Pallavaram Rows: 123936

[115/836] Processing Pallijkarani
Saved: Pallijkarani Rows: 123936

[116/836] Processing Pallikondai
Saved: Pallikondai Rows: 123936

[117/836] Processing Pallipalaiyam
Saved: Pallipalaiyam Rows: 123936

[118/836] Processing Pallipattu
Saved: Pallipattu Rows: 123936

[119/836] Processing Pallippatti
Saved: Pallippatti Rows: 123936

[120/836] Processing Palmaner
Saved: Palmaner Rows: 123936

[121/836] Processing Palni
Saved: Palni Rows: 123936

[122/836] Processing Paloncha
Saved: Paloncha Rows: 123936

[123/836] Processing Palsud
Saved: Palsud Rows: 123936

[124/836] Processing Palukudoddi
Saved: Palukudoddi Rows: 123936

[125/836] Processing Palwal
Saved: Palwal Rows: 123936

[126/836] Processing Pama
Saved: Pama Rows: 123936

[127/836] Processing Pamarru
Saved: Pamarru Rows: 123936

[128/836] Processing Pamban
Saved: Pamban Rows: 123936

[129/836] Processing Pamidi
Saved: Pamidi Rows: 123936

[130/836] Processing Pamuru
Saved: Pamuru Rows: 123936

[131/836] Processing Panagar
Saved: Panagar Rows: 123936

[132/836] Processing Panaji
Saved: Panaji Rows: 123936

[133/836] Processing Panakkudi
Saved: Panakkudi Rows: 123936

[134/836] Processing Panamarattuppatti
Saved: Panamarattuppatti Rows: 123936

[135/836] Processing Panapakkam
Saved: Panapakkam Rows: 123936

[136/836] Processing Panapur Langa
Saved: Panapur Langa Rows: 123936

[137/836] Processing Panapur
Saved: Panapur Rows: 123936

[138/836] Processing Panasapadu
Saved: Panasapadu Rows: 123936

[139/836] Processing Panchanandapur
Saved: Panchanandapur Rows: 123936

[140/836] Processing Panchgani
Saved: Panchgani Rows: 123936

[141/836] Processing Panchgram
Saved: Panchgram Rows: 123936

[142/836] Processing Panchi
Saved: Panchi Rows: 123936

[143/836] Processing Panchkula
Saved: Panchkula Rows: 123936

[144/836] Processing Panchla
Saved: Panchla Rows: 123936

[145/836] Processing Pandalkudi
Saved: Pandalkudi Rows: 123936

[146/836] Processing Pandaravadai
Saved: Pandaravadai Rows: 123936

[147/836] Processing Pandaul
Saved: Pandaul Rows: 123936

[148/836] Processing Pandhana
Saved: Pandhana Rows: 123936

[149/836] Processing Pandharpur
Saved: Pandharpur Rows: 123936

[150/836] Processing Pandhurna
Saved: Pandhurna Rows: 123936

[151/836] Processing Pandireddigudem
Saved: Pandireddigudem Rows: 123936

[152/836] Processing Pandua
Saved: Pandua Rows: 123936

[153/836] Processing Pangunattam
Saved: Pangunattam Rows: 123936

[154/836] Processing Panhar
Saved: Panhar Rows: 123936

[155/836] Processing Paniem
Saved: Paniem Rows: 123936

[156/836] Processing Panihati
Saved: Panihati Rows: 123936

[157/836] Processing Panipat
Saved: Panipat Rows: 123936

[158/836] Processing Panjampatti
Saved: Panjampatti Rows: 123936

[159/836] Processing Panjgirain Kalan
Saved: Panjgirain Kalan Rows: 123936

[160/836] Processing Panjipara
Saved: Panjipara Rows: 123936

[161/836] Processing Panna
Saved: Panna Rows: 123936

[162/836] Processing Pannaikkadu
Saved: Pannaikkadu Rows: 123936

[163/836] Processing Pannimadai
Saved: Pannimadai Rows: 123936

[164/836] Processing Panniyannur
Saved: Panniyannur Rows: 123936

[165/836] Processing Panpuli
Saved: Panpuli Rows: 123936

[166/836] Processing Panr
Saved: Panr Rows: 123936

[167/836] Processing Panrepatti
Saved: Panrepatti Rows: 123936

[168/836] Processing Panruti
Saved: Panruti Rows: 123936

[169/836] Processing Pansemal
Saved: Pansemal Rows: 123936

[170/836] Processing Panskura
Saved: Panskura Rows: 123936

[171/836] Processing Panvel
Saved: Panvel Rows: 123936

[172/836] Processing Panzgam
Saved: Panzgam Rows: 123936

[173/836] Processing Papampeta
Saved: Papampeta Rows: 123936

[174/836] Processing Papanasam
Saved: Papanasam Rows: 123936

[175/836] Processing Papireddippatti
Saved: Papireddippatti Rows: 123936

[176/836] Processing Pappakudi
Saved: Pappakudi Rows: 123936

[177/836] Processing Pappakurichchi
Saved: Pappakurichchi Rows: 123936

[178/836] Processing Pappampatti
Saved: Pappampatti Rows: 123936

[179/836] Processing Pappinissheri
Saved: Pappinissheri Rows: 123936

[180/836] Processing Papraur
Saved: Papraur Rows: 123936

[181/836] Processing Para
Saved: Para Rows: 123936

[182/836] Processing Paradarami
Saved: Paradarami Rows: 123936

[183/836] Processing Paradip Garh
Saved: Paradip Garh Rows: 123936

[184/836] Processing Paragaticherla
Saved: Paragaticherla Rows: 123936

[185/836] Processing Paraippatti
Saved: Paraippatti Rows: 123936

[186/836] Processing Paramagudi
Saved: Paramagudi Rows: 123936

[187/836] Processing Paramanandal
Saved: Paramanandal Rows: 123936

[188/836] Processing Paramankurichi
Saved: Paramankurichi Rows: 123936

[189/836] Processing Paramati
Saved: Paramati Rows: 123936

[190/836] Processing Parapatti
Saved: Parapatti Rows: 123936

[191/836] Processing Pararia
Saved: Pararia Rows: 123936

[192/836] Processing Pararia_2
Saved: Pararia_2 Rows: 123936

[193/836] Processing Parasbani
Saved: Parasbani Rows: 123936

[194/836] Processing Parasi
Saved: Parasi Rows: 123936

[195/836] Processing Parasia
Saved: Parasia Rows: 123936

[196/836] Processing Parasurampur
Saved: Parasurampur Rows: 123936

[197/836] Processing Paratdiha
Saved: Paratdiha Rows: 123936

[198/836] Processing Parauli
Saved: Parauli Rows: 123936

[199/836] Processing Paravada
Saved: Paravada Rows: 123936

[200/836] Processing Paravai
Saved: Paravai Rows: 123936

[201/836] Processing Paravur Tekkumbhagam
Saved: Paravur Tekkumbhagam Rows: 123936

[202/836] Processing Paravurkambolam
Saved: Paravurkambolam Rows: 123936

[203/836] Processing Parbata
Saved: Parbata Rows: 123936

[204/836] Processing Parbhani
Saved: Parbhani Rows: 123936

[205/836] Processing Pardi
Saved: Pardi Rows: 123936

[206/836] Processing Pardiguda
Saved: Pardiguda Rows: 123936

[207/836] Processing Pardwal
Saved: Pardwal Rows: 123936

[208/836] Processing Pareo
Saved: Pareo Rows: 123936

[209/836] Processing Pargi
Saved: Pargi Rows: 123936

[210/836] Processing Parigi
Saved: Parigi Rows: 123936

[211/836] Processing Parihara
Saved: Parihara Rows: 123936

[212/836] Processing Pariharpur
Saved: Pariharpur Rows: 123936

[213/836] Processing Pariharpur_2
Saved: Pariharpur_2 Rows: 123936

[214/836] Processing Parimpudi
Saved: Parimpudi Rows: 123936

[215/836] Processing Pariyari
Saved: Pariyari Rows: 123936

[216/836] Processing Parjuar
Saved: Parjuar Rows: 123936

[217/836] Processing Parkal
Saved: Parkal Rows: 123936

[218/836] Processing Parmanpur
Saved: Parmanpur Rows: 123936

[219/836] Processing Parol
Saved: Parol Rows: 123936

[220/836] Processing Parora
Saved: Parora Rows: 123936

[221/836] Processing Parsa
Saved: Parsa Rows: 123936

[222/836] Processing Parsa_2
Saved: Parsa_2 Rows: 123936

[223/836] Processing Parsad
Saved: Parsad Rows: 123936

[224/836] Processing Parsagarhi
Saved: Parsagarhi Rows: 123936

[225/836] Processing Parsahi Sirsia
Saved: Parsahi Sirsia Rows: 123936

[226/836] Processing Partap Tanr
Saved: Partap Tanr Rows: 123936

[227/836] Processing Partapnagar
Saved: Partapnagar Rows: 123936

[228/836] Processing Partiala
Saved: Partiala Rows: 123936

[229/836] Processing Partibanur
Saved: Partibanur Rows: 123936

[230/836] Processing Partur
Saved: Partur Rows: 123936

[231/836] Processing Paruchuru
Saved: Paruchuru Rows: 123936

[232/836] Processing Parur
Saved: Parur Rows: 123936

[233/836] Processing Parvatgiri
Saved: Parvatgiri Rows: 123936

[234/836] Processing Parvatipuram
Saved: Parvatipuram Rows: 123936

[235/836] Processing Parwaha
Saved: Parwaha Rows: 123936

[236/836] Processing Pasaul
Saved: Pasaul Rows: 123936

[237/836] Processing Pasighat
Saved: Pasighat Rows: 123936

[238/836] Processing Pasivedalajimma
Saved: Pasivedalajimma Rows: 123936

[239/836] Processing Pasraha
Saved: Pasraha Rows: 123936

[240/836] Processing Pastpar
Saved: Pastpar Rows: 123936

[241/836] Processing Pasupatikovil
Saved: Pasupatikovil Rows: 123936

[242/836] Processing Pata Ellamilli
Saved: Pata Ellamilli Rows: 123936

[243/836] Processing Pata Kalidindi
Saved: Pata Kalidindi Rows: 123936

[244/836] Processing Pata Putrela
Saved: Pata Putrela Rows: 123936

[245/836] Processing Pata Uppal
Saved: Pata Uppal Rows: 123936

[246/836] Processing Pataili
Saved: Pataili Rows: 123936

[247/836] Processing Patakakani
Saved: Patakakani Rows: 123936

[248/836] Processing Patalia
Saved: Patalia Rows: 123936

[249/836] Processing Patamundai
Saved: Patamundai Rows: 123936

[250/836] Processing Patan
Saved: Patan Rows: 123936

[251/836] Processing Patan_2
Saved: Patan_2 Rows: 123936

[252/836] Processing Patancheruvu
Saved: Patancheruvu Rows: 123936

[253/836] Processing Patapatnam
Saved: Patapatnam Rows: 123936

[254/836] Processing Patchur
Saved: Patchur Rows: 123936

[255/836] Processing Patera
Saved: Patera Rows: 123936

[256/836] Processing Pathanamthitta
Saved: Pathanamthitta Rows: 123936

[257/836] Processing Pathankot
Saved: Pathankot Rows: 123936

[258/836] Processing Pathardi
Saved: Pathardi Rows: 123936

[259/836] Processing Pathari
Saved: Pathari Rows: 123936

[260/836] Processing Patharia
Saved: Patharia Rows: 123936

[261/836] Processing Pathra
Saved: Pathra Rows: 123936

[262/836] Processing Pathraha
Saved: Pathraha Rows: 123936

[263/836] Processing Pathrajolhania
Saved: Pathrajolhania Rows: 123936

[264/836] Processing Pathri
Saved: Pathri Rows: 123936

[265/836] Processing Patiala
Saved: Patiala Rows: 123936

[266/836] Processing Patilar
Saved: Patilar Rows: 123936

[267/836] Processing Patiram
Saved: Patiram Rows: 123936

[268/836] Processing Patjirwa
Saved: Patjirwa Rows: 123936

[269/836] Processing Patlur
Saved: Patlur Rows: 123936

[270/836] Processing Patna
Saved: Patna Rows: 123936

[271/836] Processing Patnagarh
Saved: Patnagarh Rows: 123936

[272/836] Processing Patori
Saved: Patori Rows: 123936

[273/836] Processing Patpara
Saved: Patpara Rows: 123936

[274/836] Processing Patrasaer
Saved: Patrasaer Rows: 123936

[275/836] Processing Patratu
Saved: Patratu Rows: 123936

[276/836] Processing Patsanda
Saved: Patsanda Rows: 123936

[277/836] Processing Pattamadai
Saved: Pattamadai Rows: 123936

[278/836] Processing Pattanam
Saved: Pattanam Rows: 123936

[279/836] Processing Pattanam_2
Saved: Pattanam_2 Rows: 123936

[280/836] Processing Patti
Saved: Patti Rows: 123936

[281/836] Processing Pattikonda
Saved: Pattikonda Rows: 123936

[282/836] Processing Pattiswaram
Saved: Pattiswaram Rows: 123936

[283/836] Processing Pattukkottai
Saved: Pattukkottai Rows: 123936

[284/836] Processing Patut
Saved: Patut Rows: 123936

[285/836] Processing Paura Madan Singh
Saved: Paura Madan Singh Rows: 123936

[286/836] Processing Pauri
Saved: Pauri Rows: 123936

[287/836] Processing Pavittiram
Saved: Pavittiram Rows: 123936

[288/836] Processing Pavugada
Saved: Pavugada Rows: 123936

[289/836] Processing Pawai
Saved: Pawai Rows: 123936

[290/836] Processing Pawayan
Saved: Pawayan Rows: 123936

[291/836] Processing Pawni
Saved: Pawni Rows: 123936

[292/836] Processing Payakaraopeta
Saved: Payakaraopeta Rows: 123936

[293/836] Processing Payyannur
Saved: Payyannur Rows: 123936

[294/836] Processing Pebberu
Saved: Pebberu Rows: 123936

[295/836] Processing Pedana
Saved: Pedana Rows: 123936

[296/836] Processing Pedappai
Saved: Pedappai Rows: 123936

[297/836] Processing Pedavidu
Saved: Pedavidu Rows: 123936

[298/836] Processing Pedda Adsarlapalli
Saved: Pedda Adsarlapalli Rows: 123936

[299/836] Processing Pedda Kotayalanka
Saved: Pedda Kotayalanka Rows: 123936

[300/836] Processing Pedda Mupparam
Saved: Pedda Mupparam Rows: 123936

[301/836] Processing Pedda Nindrakolanu
Saved: Pedda Nindrakolanu Rows: 123936

[302/836] Processing Pedda Pendyala
Saved: Pedda Pendyala Rows: 123936

[303/836] Processing Pedda Penki
Saved: Pedda Penki Rows: 123936

[304/836] Processing Pedda Vegi
Saved: Pedda Vegi Rows: 123936

[305/836] Processing Peddaboddepalle
Saved: Peddaboddepalle Rows: 123936

[306/836] Processing Peddakurapadu
Saved: Peddakurapadu Rows: 123936

[307/836] Processing Peddannavaripalle
Saved: Peddannavaripalle Rows: 123936

[308/836] Processing Peddapadu
Saved: Peddapadu Rows: 123936

[309/836] Processing Peddapalle
Saved: Peddapalle Rows: 123936

[310/836] Processing Peddapalli
Saved: Peddapalli Rows: 123936

[311/836] Processing Peddapuram
Saved: Peddapuram Rows: 123936

[312/836] Processing Peddapuram_2
Saved: Peddapuram_2 Rows: 123936

[313/836] Processing Peddavadlapudi
Saved: Peddavadlapudi Rows: 123936

[314/836] Processing Pehowa
Saved: Pehowa Rows: 123936

[315/836] Processing Pelagor
Saved: Pelagor Rows: 123936

[316/836] Processing Pen
Saved: Pen Rows: 123936

[317/836] Processing Penaballi
Saved: Penaballi Rows: 123936

[318/836] Processing Penamaluru
Saved: Penamaluru Rows: 123936

[319/836] Processing Pendekallu
Saved: Pendekallu Rows: 123936

[320/836] Processing Pendurti
Saved: Pendurti Rows: 123936

[321/836] Processing Pennadam
Saved: Pennadam Rows: 123936

[322/836] Processing Pennagaram
Saved: Pennagaram Rows: 123936

[323/836] Processing Pentapadu Kasba
Saved: Pentapadu Kasba Rows: 123936

[324/836] Processing Penuganchiprolu

In [1]:
import os

path = r"D:\Weather"

print(os.listdir(path))

['archive.zip', 'Extracted', 'hadoop.dll', 'KT Document – Conversion of Weather CSV Dataset to Parquet.pdf', 'KT Document – CSV to Parquet Conversion for Bronze Layer.pdf', 'OpenJDK17U-jdk_x64_windows_hotspot_17.0.19_10.msi', 'Parquet', 'Python-3.11.15.tar.xz', 'python-manager-26.3.msix', 'temp_city.csv', 'temp_csv', 'winutils.exe', 'w_d_1']

In [15]:
import zipfile

zip_path = r"D:\Weather\archive.zip"

with zipfile.ZipFile(zip_path, 'r') as z:
    files = z.namelist()

for f in files:
    if "Weather_Data_Scraping_and_Analysis" in f:
        print(f)

Weather_Data_Scraping_and_Analysis/weather-data-scraping-and-analysis.ipynb
Weather_Data_Scraping_and_Analysis/weather.csv

In [18]:
# remove unnecessary index column

weather_df = weather_df.drop(
    columns=["Unnamed: 0"]
)

weather_df.head()

        city      lat      lng
0      Delhi  28.6100  77.2300
1     Mumbai  19.0761  72.8775
2    Kolkata  22.5675  88.3700
3  Bangalore  12.9789  77.5917
4    Chennai  13.0825  80.2750

In [19]:
weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5933 entries, 0 to 5932
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   city    5933 non-null   object
 1   lat     5933 non-null   float64
 2   lng     5933 non-null   float64
dtypes: float64(2), object(1)
memory usage: 139.2+ KB

In [20]:
import os

output_path = r"D:\Weather\Parquet\city_master"

os.makedirs(output_path, exist_ok=True)

In [21]:
output_file = os.path.join(
    output_path,
    "city_master.parquet"
)


weather_df.to_parquet(
    output_file,
    engine="pyarrow",
    compression="snappy",
    index=False
)

print("SUCCESS")
print(output_file)

SUCCESS
D:\Weather\Parquet\city_master\city_master.parquet

In [22]:
test = pd.read_parquet(output_file)

print(test.shape)

test.head()

(5933, 3)

        city      lat      lng
0      Delhi  28.6100  77.2300
1     Mumbai  19.0761  72.8775
2    Kolkata  22.5675  88.3700
3  Bangalore  12.9789  77.5917
4    Chennai  13.0825  80.2750

In [24]:
import pandas as pd

test = pd.read_parquet(
    r"D:\Weather\Parquet\w_d_1\Abbigeri.parquet"
)

test.head()

,Unnamed: 0,date,temperature_2m,relative_humidity_2m,dew_point_2m,apparent_temperature,precipitation,rain,snowfall,snow_depth,...,cloud_cover,cloud_cover_low,cloud_cover_mid,cloud_cover_high,wind_speed_10m,wind_speed_100m,wind_direction_10m,wind_direction_100m,wind_gusts_10m,city
0,0,2010-01-01 00:00:00+00:00,19.619501,91.34468,18.169500,21.770710,0.0,0.0,0.0,0.0,...,1.8,2.0,0.0,0.0,5.760000,12.313893,90.000000,105.25517,10.080000,Abbigeri
1,1,2010-01-01 01:00:00+00:00,19.369501,91.04204,17.869501,21.319320,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,6.214563,14.154915,79.992090,97.30567,12.599999,Abbigeri
2,2,2010-01-01 02:00:00+00:00,19.669500,88.24221,17.669500,21.166674,0.0,0.0,0.0,0.0,...,1.8,0.0,3.0,0.0,8.707238,16.575644,82.875084,92.48950,16.919998,Abbigeri
3,3,2010-01-01 03:00:00+00:00,21.669500,78.01420,17.669500,22.908940,0.0,0.0,0.0,0.0,...,1.8,0.0,3.0,0.0,10.464798,15.480000,86.054890,90.00000,24.119999,Abbigeri
4,4,2010-01-01 04:00:00+00:00,23.719501,67.81361,17.419500,24.480686,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,12.979984,16.622490,93.179770,94.96966,31.319998,Abbigeri

In [26]:
import os
import pandas as pd

base_path = r"D:\Weather\Parquet"


for folder in ["w_d_1","w_d_2","w_d_3"]:

    folder_path = os.path.join(base_path, folder)

    print("Processing:", folder)

    for file in os.listdir(folder_path):

        if file.endswith(".parquet"):

            file_path = os.path.join(folder_path,file)

            # read parquet
            df = pd.read_parquet(file_path)

            # get city name from filename
            city = file.replace(".parquet","")

            # add city column
            df["city"] = city

            # overwrite parquet
            df.to_parquet(
                file_path,
                engine="pyarrow",
                compression="snappy",
                index=False
            )

            print("Done:",city)

print("ALL COMPLETED")

Processing: w_d_1
Done: Abbigeri
Done: Abdullahnagar
Done: Abhayapuri
Done: Abhia
Done: Abhwar
Done: Abiramam
Done: Ablu
Done: Abohar
Done: Abu
Done: Achaljamu
Done: Achampet
Done: Acharipallam
Done: Achchippatti
Done: Achhnera
Done: Adalaj
Done: Adalpur
Done: Adamankottai
Done: Adampur
Done: Addanki
Done: Adigappadi
Done: Adigaratti
Done: Adigoppula
Done: Adilabad
Done: Adivala
Done: Adiyakkamangalam
Done: Adoni
Done: Adra
Done: Advi Devalpalli
Done: Adyar
Done: Afzala
Done: Afzalpur
Done: Agadallanka
Done: Agadi
Done: Agar
Done: Agaram
Done: Agarpur
Done: Agartala
Done: Aginiparru
Done: Agiripalle
Done: Agra
Done: Agwar
Done: Ahirauliya
Done: Ahiro
Done: Ahmadabad
Done: Ahmadnagar
Done: Ahmadpur
Done: Ahmedabad
Done: Aigali
Done: Ainapur
Done: Aizawl
Done: Ajaigarh
Done: Ajas
Done: Ajjampur
Done: Ajjanahalli
Done: Ajjipuram
Done: Ajmer
Done: Ajnala
Done: Ajodhya
Done: Akalgarh
Done: Akanavaritota
Done: Akbarpur
Done: Akbarpur_2
Done: Akhnur
Done: Akividu
Done: Aklvidu
Done: Akola
Done: Akora
Done: Akot
Done: Alagappapuram
Done: Alagarai
Done: Alamnagar
Done: Alampalaiyam
Done: Alampur Gonpura
Done: Alampur
Done: Alampur_2
Done: Alampur_3
Done: Alamuru
Done: Aland
Done: Alanganallur
Done: Alangayam
Done: Alangudi
Done: Alangulam
Done: Alasandigutta
Done: Alauli
Done: Alawalpur
Done: Alawandi
Done: Aldona
Done: Algun
Done: Aliganj
Done: Aligarh
Done: Alipur Duar
Done: Alipur
Done: Alipura
Done: Aliyabad
Done: Allagadda
Done: Allahdurg
Done: Allahpur
Done: Alleppey
Done: Allinagaram
Done: Allur
Done: Alluru
Done: Almel
Done: Almora
Done: Alnavar
Done: Alukkuli
Done: Alur
Done: Alwa Tirunagari
Done: Alwal
Done: Alwar
Done: Alwarkurichchi
Done: Alwaye
Done: Amadalli
Done: Amaha
Done: Amalapuram
Done: Amalner
Done: Amangal
Done: Amanganj
Done: Amarapuuram
Done: Amaravati
Done: Amaravati_2
Done: Amarchinta
Done: Amari
Done: Amarpatan
Done: Amarpur
Done: Amarwara
Done: Amayan
Done: Amba Icharua
Done: Ambajogai
Done: Ambala
Done: Ambala_2
Done: Ambara
Done: Ambasamudram
Done: Ambattur
Done: Ambatturai
Done: Ambhua
Done: Amgachia
Done: Amha
Done: Amiawar
Done: Amingaon
Done: Amingarh
Done: Aminpur
Done: Amjhar
Done: Amjhera
Done: Amla
Done: Ammanabrolu
Done: Ammapettai
Done: Ammapettai_2
Done: Ammavarikuppam
Done: Ammur
Done: Amodei
Done: Amrabad
Done: Amravati
Done: Amritsar
Done: Amroha
Done: Amta
Done: Amtala
Done: Amtala_2
Done: Amudalapalle
Done: Amudalavalasa
Done: Amwa Majhar
Done: Anaiyur
Done: Anakapalle
Done: Anakaputtur
Done: Anamalais
Done: Anand
Done: Anandpur
Done: Anandpur_2
Done: Anandpur_3
Done: Ananipalle
Done: Anantapalle
Done: Anantapur
Done: Anantarazupeta
Done: Anantasagaram
Done: Anantpur
Done: Anavatti
Done: Andal
Done: Andanappettai
Done: Andhana
Done: Andhra Tharhi
Done: Andipalaiyam
Done: Andippatti
Done: Andiyappanur
Done: Anekal
Done: Angalakuduru Malepalle
Done: Angalakurichchi
Done: Angallu
Done: Angamali
Done: Angichettippalaiyam
Done: Angul
Done: Angwali
Done: Anjad
Done: Anjangaon
Done: Anjehalli
Done: Anjukulippatti
Done: Anjuna
Done: Ankalgi
Done: Ankireddikuntapalem
Done: Ankli
Done: Ankola
Done: Annamalainagar
Done: Annaram
Done: Annavasal
Done: Anndevarapeta
Done: Annigeri
Done: Annur
Done: Antardipa
Done: Antarvedi
Done: Antarvedipalem
Done: Antri
Done: Anuppampattu
Done: Anuppur
Done: Aphaur
Done: Apparaopeta
Done: Appukkudal
Done: Arachchalur
Done: Arajpur
Done: Arakere
Done: Arakeri
Done: Arambagh
Done: Arambakkam
Done: Aranda
Done: Arani
Done: Arantangi
Done: Aranya Kalan
Done: Araria
Done: Arasur
Done: Aravakkurichchi
Done: Aravelli
Done: Arcot
Done: Arda
Done: Areraj
Done: Arimalam
Done: Ariyalur
Done: Arkonam
Done: Arma
Done: Armur
Done: Arni
Done: Arniya
Done: Aroali
Done: Arohi
Done: Aron
Done: Arrah
Done: Arrapalli
Done: Arsali
Done: Arsikere
Done: Arugollu
Done: Arumanallur
Done: Arumbavur
Done: Arumuganeri
Done: Aruppukkottai
Done: Arutla
Done: Aruvikkara
Done: Arwal
Done: Asafabad
Done: Asahni
Done: Asakapalle
Done: Asansol
Done: Asarganj
Done: Asarhi
Done: Ashoknagar
Done: Ashta
Done: Ashwaraopeta
Done: Asthanwan
Done: Aswapuram
Done: Atari
Done: Atchampeta
Done: Athagarh
Done: Athar
Done: Atharga
Done: Athni
Done: Atlapadu
Done: Atmakur
Done: Atmakuru
Done: Atmakur_2
Done: Atmakur_3
Done: Atmakur_4
Done: Atner
Done: Attanur
Done: Attappampatti
Done: Attibele
Done: Attili
Done: Attimarappatti
Done: Attingal
Done: Attippattu
Done: Attur
Done: Atturkuppam
Done: Auhar Sheikh
Done: Aurad
Done: Aurahi
Done: Aurahi_2
Done: Aurahi_3
Done: Aurahi_4
Done: Aurangabad
Done: Aurangabad_2
Done: Auria
Done: Auta
Done: Avadattur
Done: Avadi
Done: Avalepalli
Done: Avalpundurai
Done: Avalurpet
Done: Avanashipalaiyam
Done: Avanigadda
Done: Avaniyapuram
Done: Awankh
Done: Ayas
Done: Ayikudi
Done: Ayirapuram
Done: Ayodhyapattanam
Done: Ayyagarpet
Done: Ayyampalaiyam
Done: Ayyampettai
Done: Azamnagar
Done: Azizpur Chande
Done: Baba Bakala
Done: Babai Kalan
Done: Babai
Done: Babhanganwa
Done: Babhangaon
Done: Babhangawan
Done: Babhani Bholwa
Done: Babhantoli
Done: Babhniyawan
Done: Babhnoul
Done: Babura
Done: Bachchannapet
Done: Bachhauta
Done: Bachra
Done: Bada Barabil
Done: Badagabettu
Done: Badanahatti
Done: Badantola
Done: Badarpur
Done: Badarwas
Done: Badepalli
Done: Badkulla
Done: Badnawar
Done: Badru Khan
Done: Baduria
Done: Baduriatola
Done: Badurpalle
Done: Badvel
Done: Bag
Done: Bagaha
Done: Bagahi
Done: Bagalkot
Done: Bagalur
Done: Bagalur_2
Done: Bagalvad
Done: Bagaura
Done: Bagchini
Done: Bagepalli
Done: Bageshwar
Done: Bagewadi
Done: Bagha Purana
Done: Baghambarpur
Done: Baghant
Done: Baghauni
Done: Baghduma
Done: Baghra
Done: Bagli
Done: Bagnan
Done: Bagula
Done: Bahadarpur
Done: Bahadurganj
Done: Bahadurpur
Done: Bahagalpur
Done: Baharampur
Done: Baharu
Done: Baheri
Done: Bahraigh
Done: Bahutal
Done: Baidyabati
Done: Baihar
Done: Baikatpur
Done: Baikunthapur
Done: Baikunthpur
Done: Bail-Hongal
Done: Bairagnia
Done: Bairia
Done: Bairia_2
Done: Bairiya
Done: Bairo
Done: Baisa
Done: Baisuhalli
Done: Baj Baj
Done: Bajala
Done: Bajpe
Done: Bajwara
Done: Bakarpur Ogairah
Done: Bakharia
Done: Bakhra
Done: Bakhri
Done: Bakhtiyarpur
Done: Bakwa
Done: Baladharmaram
Done: Balakrishnanpatti
Done: Balangir
Done: Balarampur
Done: Balarampur_2
Done: Balasamudram
Done: Balasore
Done: Balaungi
Done: Baldeogarh
Done: Balgudar
Done: Balha
Done: Balhapur
Done: Bali
Done: Balia
Done: Baligaon
Done: Balighattam
Done: Balkonda
Done: Ballia
Done: Baltara
Done: Balua Rampur
Done: Balua
Done: Balugan
Done: Balumath
Done: Balupur
Done: Balurghat
Done: Balvadi
Done: Bamaiya Harlal
Done: Bamaur
Done: Bamhni
Done: Bamora
Done: Banagi
Done: Banapur
Done: Banaso
Done: Banavar
Done: Banbhag
Done: Banda
Done: Bandalli
Done: Bandamurlanka
Done: Bandipura
Done: Bandlaguda
Done: Bandora
Done: Bandwar
Done: Banga
Done: Bangalore
Done: Banganapalle
Done: Bangaon
Done: Bangaon_2
Done: Bangaon_3
Done: Bangawan
Done: Banhatti
Done: Bank
Done: Bankapur
Done: Bankheri
Done: Banki
Done: Banki_2
Done: Bankra
Done: Bankura
Done: Banni
Done: Bannur
Done: Bansbari
Done: Bansbaria
Done: Banswada
Done: Banta
Done: Bantval
Done: Banu Chhapra
Done: Bapatla
Done: Bar Bigha
Done: Bara Belun
Done: Bara Khurd
Done: Bara Malehra
Done: Bara
Done: Baragaon
Done: Baragaon_2
Done: Barah
Done: Barahari
Done: Barahbatta
Done: Barahi
Done: Barahkurwa
Done: Barahpur
Done: Barahra
Done: Barai
Done: Baraidih
Done: Barajor
Done: Barakpur
Done: Baramula
Done: Baraon
Done: Bararam
Done: Barari
Done: Barasat
Done: Barauli
Done: Bara_2
Done: Barbana
Done: Barddhaman
Done: Bardiha Turki
Done: Bardipuram
Done: Bareh
Done: Bareilly
Done: Barela
Done: Baretha
Done: Bargaon
Done: Bargaon_2
Done: Bargarh
Done: Barghat
Done: Bargur
Done: Barhagarh
Done: Barhampur
Done: Barhampur_2
Done: Barhampur_3
Done: Barharia
Done: Barharwa Kalan
Done: Barharwa
Done: Barhauna
Done: Barhauna_2
Done: Barhi
Done: Barhiya
Done: Barhi_2
Done: Barhi_3
Done: Barhi_4
Done: Bari
Done: Bariariya Tola Rajpur
Done: Bariariya
Done: Bariarpur Kandh
Done: Bariarpur
Done: Bariarpur_2
Done: Barigarh
Done: Bariyarpur
Done: Barjhar
Done: Barjora
Done: Barka Gaon
Done: Barka Parbatta
Done: Barkagaon
Done: Barki Ballia
Done: Barki Saria
Done: Barkot
Done: Barkuhi
Done: Barnagar
Done: Barnala
Done: Barnaon
Done: Barni
Done: Barnia
Done: Baro
Done: Barod
Done: Baroda
Done: Baroni Khurd
Done: Barpathar
Done: Barpeta
Done: Barsaun
Done: Baruari
Done: Barud
Done: Barughutu
Done: Baruipur
Done: Barun
Done: Baruni
Done: Barwadih
Done: Barwah
Done: Barwan
Done: Barwani
Done: Barwat Pasrain
Done: Basaha
Done: Basaithi
Done: Basantpur
Done: Basaon
Done: Basapatna
Done: Basarh
Done: Basatpur
Done: Basavakalyan
Done: Basavana Bagevadi
Done: Basbiti
Done: Basdeopur
Done: Basi
Done: Basirhat
Done: Basmanpur
Done: Basoda
Done: Basopatti
Done: Basrur
Done: Bassian
Done: Basudebpur
Done: Basudebpur_2
Done: Batala
Done: Bataredh
Done: Bathnaha
Done: Battulapalle
Done: Baturbari
Done: Baud
Done: Baulia
Done: Bauria
Done: Bawali
Done: Bayaram
Done: Baynala
Done: Bayyanagudem
Done: Bayyavaram
Done: Bazid Chak Kasturi
Done: Bazidpur
Done: Beawar
Done: Begamganj
Done: Begampur
Done: Begampur_2
Done: Begowal
Done: Begusarai
Done: Behat
Done: Beko
Done: Bela Simri
Done: Bela
Done: Beladi
Done: Belagal
Done: Belagola
Done: Belakoba
Done: Belakvadi
Done: Belampalli
Done: Belao
Done: Belari
Done: Belauncha
Done: Belaur
Done: Bela_2
Done: Bela_3
Done: Beldanga
Done: Beldanga_2
Done: Beldaur
Done: Belgaum
Done: Belhatti
Done: Belhi
Done: Bellamkonda
Done: Bellary
Done: Belludi
Done: Belo
Done: Belonia
Done: Belpara
Done: Belpukur
Done: Belsand
Done: Belsandi Tara
Done: Belsara
Done: Beltangadi
Done: Belur
Done: Belur_2
Done: Belvadi
Done: Belwa
Done: Belwara
Done: Benaulim
Done: Bendapudi
Done: Bendrahalli
Done: Benipati
Done: Beohari
Done: Berasia
Done: Berchha
Done: Berikai
Done: Bermo
Done: Berubari
Done: Besagarahalli
Done: Besarh
Done: Betamcherla
Done: Betigeri
Done: Betma
Done: Betmangala
Done: Bettiah
Done: Betul Bazar
Done: Beur
Done: Beypore
Done: Bhabanipur
Done: Bhabhua
Done: Bhachhi Asli
Done: Bhachhi
Done: Bhadarwah
Done: Bhadas
Done: Bhadaur
Done: Bhado Khara
Done: Bhadrachalam
Done: Bhadrakh
Done: Bhadravati
Done: Bhadreswar
Done: Bhadsara
Done: Bhadwar
Done: Bhagabanpur
Done: Bhagalpur
Done: Bhagatpur
Done: Bhagirathpur
Done: Bhagsar
Done: Bhagta
Done: Bhagwangola
Done: Bhagwanpur Desua
Done: Bhagwatpur
Done: Bhai Rupa
Done: Bhainsa
Done: Bhainsahi
Done: Bhainsdehi
Done: Bhainsoda
Done: Bhaisalotan
Done: Bhakua
Done: Bhalaiana
Done: Bhalki
Done: Bhalpatti
Done: Bhalswa Jahangirpur
Done: Bhandarso
Done: Bhander
Done: Bhangar
Done: Bhangha
Done: Bhanghi
Done: Bhankarpur
Done: Bhanpura
Done: Bhansia
Done: Bhanukumari
Done: Bhanumukkala
Done: Bhanuvalli
Done: Bhararisain
Done: Bharatpur
Done: Bhargaon
Done: Bharhopur
Done: Bharno
Done: Bharokhara
Done: Bharra
Done: Bharuch
Done: Bharweli
Done: Bhasaula Danapur
Done: Bhasawar
Done: Bhataulia
Done: Bhatinda
Done: Bhatkal
Done: Bhatkhori
Done: Bhatpalli
Done: Bhatpara
Done: Bhatpuri
Done: Bhatranha
Done: Bhattiprolu
Done: Bhaur
Done: Bhauradah
Done: Bhavani
Done: Bhavnagar
Done: Bhawanandpur
Done: Bhawanigarh
Done: Bhawanipatna
Done: Bhawanipur Rajdham
Done: Bhawanipur
Done: Bhawanipur_2
Done: Bhawanipur_3
Done: Bhayandar
Done: Bheja
Done: Bhelsi
Done: Bhikhi
Done: Bhikkiwind Uttar
Done: Bhilai
Done: Bhilai_2
Done: Bhilwara
Done: Bhimadolu
Done: Bhimavaram
Done: Bhimunipatnam
Done: Bhind
Done: Bhiraha
Done: Bhirua
Done: Bhit Bhagwanpur
Done: Bhitarwar
Done: Bhiwandi
Done: Bhiwani
Done: Bhogapuram
Done: Bhogpur
Done: Bhoj
Done: Bhojpur Jadid
Done: Bhojpur Kadim
Done: Bholsar
Done: Bhongir
Done: Bhopal
Done: Bhopatpur
Done: Bhuban
Done: Bhubaneshwar
Done: Bhucho Mandi
Done: Bhui
Done: Bhuj
Done: Bhulath Gharbi
Done: Bhulwal
Done: Bhusaval
Done: Biaora
Done: Bibhutpur
Done: Bibipet
Done: Bichkunda
Done: Bidar
Done: Biddupur
Done: Bideipur
Done: Bihar
Done: Bihariganj
Done: Bihat
Done: Bihpur
Done: Bihpuriagaon
Done: Bihta
Done: Bijai
Done: Bijaipur
Done: Bijapur
Done: Bijawar
Done: Bijaynagar
Done: Bijbiara
Done: Bijeraghogarh
Done: Bijni
Done: Bikaner
Done: Bikkatti
Done: Bikkavolu
Done: Biknur
Done: Bikramganj
Done: Bikrampur Bande
Done: Bilasipara
Done: Bilaspur
Done: Bilaspur_2
Done: Bilaua
Done: Bilauri
Done: Bilehra
Done: Bilga
Done: Bilgi
Done: Billapadu
Done: Bilpura
Done: Bimawan
Done: Bimgal
Done: Bimun
Done: Bina
Done: Bind
Done: Bindki
Done: Binka
Done: Binnaguri
Done: Bir
Done: Birdaban
Done: Birhana
Done: Birmitrapur
Done: Birnagar
Done: Birpur Barapatti Pindraun
Done: Birpur
Done: Birpur_2
Done: Birpur_3
Done: Birpur_4
Done: Birpur_5
Done: Birsinghpur
Done: Birur
Done: Bisaria
Done: Bisaul
Done: Bishamagiri
Done: Bishenpur
Done: Bishnah
Done: Bishnupur
Done: Bishunpur Hakimabad
Done: Bishunpur Sundar
Done: Bishunpur
Done: Bishunpura
Done: Bishunpur_2
Done: Bishunpur_3
Done: Bishunpur_4
Done: Bishunpur_5
Done: Bistan
Done: Bistaria
Done: Biswanath Chariali
Done: Bithan
Done: Bithauli
Done: Bobbili
Done: Bobil
Done: Bobleshwar
Done: Bochaha
Done: Bodagudipadu
Done: Boddikurapadu
Done: Bodhan
Done: Bodinayakkanur
Done: Bodippatti
Done: Bodupal
Done: Boha
Done: Bokakhat
Done: Bokaro
Done: Bolpur
Done: Bomareddipalli
Done: Bommagondanahalli
Done: Bommarbettu
Done: Bommayapalaiyam
Done: Bondada
Done: Bongaigaon
Done: Bora
Done: Borgampad
Done: Borgaon
Done: Boriguma
Done: Borim
Done: Borio
Done: Borna
Done: Borne
Done: Bowringpet
Done: Brahmadesam
Done: Brahmana Periya Agraharam
Done: Brahmanandapuram
Done: Brahmapur
Done: Brajarajnagar
Done: Bramhabarada
Done: Bucheya
Done: Buchireddipalem
Done: Budalur
Done: Budamangalam
Done: Budanur
Done: Budaun
Done: Buddayyakota
Done: Buddh Gaya
Done: Budha Theh
Done: Budhlada
Done: Budhma
Done: Budhni
Done: Budili
Done: Bugganipalle
Done: Buguda
Done: Bukkapatnam
Done: Bukkarayasamudram
Done: Bulandshahr
Done: Bundala
Done: Bundala_2
Done: Bundehra
Done: Bundi
Done: Bundu
Done: Buram
Done: Burhanpur
Done: Burhar
Done: Burhia Dhanghatta
Done: Burla
Done: Buttar
Done: Buttayagudem
Done: Buxar
Done: Byadgi
Done: Byahatti
Done: Byatarayanpur
Done: Calicut
Done: Candolim
Done: Cannanore
Done: Cawnpore
Done: Chabal Kalan
Done: Chada
Done: Chadchan
Done: Chagalamarri
Done: Chagallu
Done: Chahatpur
Done: Chailaha
Done: Chainpur
Done: Chaita
Done: Chaital
Done: Chak Habib
Done: Chak Husaini
Done: Chak Pahar
Done: Chak That
Done: Chakai
Done: Chakand
Done: Chakapara
Done: Chakdaha
Done: Chakia
Done: Chakicherla
Done: Chakla Waini
Done: Chakradharpur
Done: Chakwai
Done: Chalgeri
Done: Chalkari
Done: Challakere
Done: Challapalle
Done: Chaltabaria
Done: Chalungalpadam
Done: Chamarru
Done: Champadanga
Done: Champahati
Done: Champapur
Done: Champdani
Done: Champua
Done: Chamrajnagar
Done: Chamtha
Done: Chanaur
Done: Chand Chaur
Done: Chanda
Done: Chandankiari
Done: Chandannagar
Done: Chandauli
Done: Chandera
Done: Chanderi
Done: Chandhaus
Done: Chandi
Done: Chandia
Done: Chandigarh
Done: Chandili
Done: Chandi_2
Done: Chandla
Done: Chandpur
Done: Chandpura
Done: Chandpur_2
Done: Chandragiri
Done: Chandrakona
Done: Chandralapadu
Done: Chandreru
Done: Chandur
Done: Chandwa
Done: Chandwara
Done: Changanacheri
Done: Channagiri
Done: Channapatna
Done: Channarayapatna
Done: Channubanda
Done: Chanp
Done: Chanwari
Done: Chaoke
Done: Chapalamadugu
Done: Chapar
Done: Chapra
Done: Chapra_2
Done: Charabidya
Done: Charakunda
Done: Charaut
Done: Charkhari
Done: Charkhi Dadri
Done: Charne
Done: Charthawal
Done: Charuanwan
Done: Chas
Done: Chatia
Done: Chatra Gobraura
Done: Chatra
Done: Chaugain
Done: Chaukhata
Done: Chauki Hasan Chauki Makhdum
Done: Chauki
Done: Chausa
Done: Chausa_2
Done: Chautapal
Done: Chautham
Done: Chavakkad
Done: Chavuttahalli
Done: Chawalhati
Done: Chebrolu
Done: Chebrolu_2
Done: Chegur
Done: Chegurumomadi
Done: Chembagaramanpudur
Done: Chengam
Done: Chengannur
Done: Chennai
Done: Chennampatti
Done: Chennayyanakote
Done: Chennimalai
Done: Chennur
Done: Chennur_2
Done: Cherakhera
Done: Cheramkod
Done: Cheran
Done: Cherial
Done: Chero
Done: Cherrapunji
Done: Chettikulam
Done: Chettimangurichchi
Done: Chettinayakkanpatti
Done: Chettipalaiyam
Done: Chettipalaiyam_2
Done: Chettipulam
Done: Chettiyapatti
Done: Chewara
Done: Cheyyar
Done: Chhajli
Done: Chhapera
Done: Chhapia
Done: Chhapra Bahas
Done: Chhapra
Done: Chhatapur
Done: Chhatarpur
Done: Chhindwara
Done: Chianki
Done: Chicacole
Done: Chicalim
Done: Chichli
Done: Chicholi
Done: Chidambaram
Done: Chik Ballapur
Done: Chikhli Kalan
Done: Chikitigarh
Done: Chikkala
Done: Chikkarampalaiyam
Done: Chikkerur
Done: Chikmagalur
Done: Chiknayakanhalli
Done: Chikni
Done: Chikni_2
Done: Chikodi
Done: Chilakalurupet
Done: Chilakhana
Done: Chilamatturu
Done: Chilkuru
Done: Chilmil
Done: Chilpur
Done: Chimakurti
Done: Chimalapadu
Done: Chinaur
Done: Chinchali
Done: Chinchinim
Done: Chincholi
Done: Chinchvad
Done: Chingleput
Done: Chinna Annaluru
Done: Chinna Ganjam
Done: Chinna Gollapalem
Done: Chinna Kalaiyamputtur
Done: Chinna Mupparam
Done: Chinna Mushidivada
Done: Chinna Orampadu
Done: Chinna Salem
Done: Chinnachauku
Done: Chinnakkampalaiyam
Done: Chinnakkavundanur
Done: Chinnalapatti
Done: Chinnamandem
Done: Chinnamanur
Done: Chinnampalaiyam
Done: Chinnasekkadu
Done: Chinnatadagam
Done: Chinnavadampatti
Done: Chinnayagudem
Done: Chintakommadinne
Done: Chintakunta
Done: Chintalapalle
Done: Chintalapudi
Done: Chintalavadi
Done: Chintamani
Done: Chintapalle
Done: Chipurupalle
Done: Chirak
Done: Chirala
Done: Chitaldrug
Done: Chitapur
Done: Chitarpur
Done: Chitauria
Done: Chitrada
Done: Chittandikavundanur
Done: Chittaranjan
Done: Chittarkottal
Done: Chittaurgarh
Done: Chittayankottai
Done: Chittoor
Done: Chittur
Done: Chitvel
Done: Chityal
Done: Chodavaram
Done: Chodavaram_2
Done: Chokkalingapuram
Done: Chokkampatti
Done: Chokkanathapuram
Done: Cholavandan
Done: Cholavaram
Done: Chonthrhu
Done: Chopadandi
Done: Chorhat
Done: Chota Mollakhali
Done: Chudamani
Done: Chuhal
Done: Chuhr Chak
Done: Chunakhali
Done: Churi
Done: Closepet
Done: Coimbatore
Done: Colangute
Done: Colgong
Done: Conjeeveram
Done: Contai
Done: Coondapoor
Done: Coonoor
Done: Corgao
Done: Coringa
Done: Cortalim
Done: Cossimbazar
Done: Cuddalore
Done: Cuddapah
Done: Cumbum
Done: Cuncolim
Done: Curchorem
Done: Curti
Done: Curtorim
Done: Cuttack
Done: Dabhaura
Done: Daboh
Done: Dabra
Done: Dachepalle
Done: Dagarua
Done: Dagmara
Done: Daharia
Done: Daharia_2
Done: Dahi
Done: Dahibhat Madhopur
Done: Dahua
Done: Daita
Done: Dakhram
Done: Dala
Done: Dalan
Done: Dalavaypattanam
Done: Dalawarpur
Done: Dalippur
Done: Dalkola
Done: Dalli Rajhara
Done: Dalsingh Sarai
Done: Daltonganj
Done: Dam Dam
Done: Damal
Done: Damalcheruvu
Done: Daman
Done: Damarcherla
Done: Damargidda
Done: Dambal
Done: Damdama
Done: Dammapeta
Done: Dammennu
Done: Damoh
Done: Damonojodi
Done: Damu
Done: Damua
Done: Danau Kandimarg
Done: Dandeli
Done: Dandkhora
Done: Danwan
Done: Daparkha
Done: Dara
Done: Darauli
Done: Darbhanga
Done: Dari
Done: Darihat
Done: Darjeeling
Done: Darmaha
Done: Daroji
Done: Darpa
Done: Darsi
Done: Darsur
Done: Darwa
Done: Dasai
Done: Dasarhalli
Done: Dasaut
Done: Dasnapur
Done: Dasraha Bhograjpur
Done: Dasuya
Done: Datia
Done: Datian
Done: Datiana
Done: Datoda
Done: Dattapara
Done: Dattapulia
Done: Daudnagar
Done: Daulatnagar
Done: Daulatpur
Done: Davangere
Done: Davorlim
Done: Davuluru
Done: Dayalpur Sapha
Done: Dayalpur
Done: Debagram
Done: Degana
Done: Dehra Dun
Done: Dehri
Done: Dehri_2
Done: Dehti
Done: Delhi Cantonment
Done: Delhi
Done: Denduluru
Done: Deo
Done: Deodha
Done: Deodora
Done: Deodrug
Done: Deogarh
Done: Deoghar
Done: Deokali
Done: Deori Khas
Done: Deoria
Done: Depalpur
Done: Dera Baba Nanak
Done: Dergaon
Done: Desavilakku
Done: Deshnur
Done: Desri
Done: Devadanappatti
Done: Devakottai
Done: Devanakavundanur
Done: Devanakonda
Done: Devanangurichchi
Done: Devanhalli
Done: Devapur
Done: Devarapalle
Done: Devarapalle_2
Done: Devarkonda
Done: Devarshola
Done: Devendranagar
Done: Devgeri
Done: Devi Hosur
Done: Devikapuram
Done: Devipattinam
Done: Devmaudaldal
Done: Dewangarh
Done: Dewas
Done: Dhabauli

In [29]:
df = pd.read_parquet(
r"D:\Weather\Parquet\w_d_1\Abbigeri.parquet"
)

df.head()

,Unnamed: 0,date,temperature_2m,relative_humidity_2m,dew_point_2m,apparent_temperature,precipitation,rain,snowfall,snow_depth,...,cloud_cover,cloud_cover_low,cloud_cover_mid,cloud_cover_high,wind_speed_10m,wind_speed_100m,wind_direction_10m,wind_direction_100m,wind_gusts_10m,city
0,0,2010-01-01 00:00:00+00:00,19.619501,91.34468,18.169500,21.770710,0.0,0.0,0.0,0.0,...,1.8,2.0,0.0,0.0,5.760000,12.313893,90.000000,105.25517,10.080000,Abbigeri
1,1,2010-01-01 01:00:00+00:00,19.369501,91.04204,17.869501,21.319320,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,6.214563,14.154915,79.992090,97.30567,12.599999,Abbigeri
2,2,2010-01-01 02:00:00+00:00,19.669500,88.24221,17.669500,21.166674,0.0,0.0,0.0,0.0,...,1.8,0.0,3.0,0.0,8.707238,16.575644,82.875084,92.48950,16.919998,Abbigeri
3,3,2010-01-01 03:00:00+00:00,21.669500,78.01420,17.669500,22.908940,0.0,0.0,0.0,0.0,...,1.8,0.0,3.0,0.0,10.464798,15.480000,86.054890,90.00000,24.119999,Abbigeri
4,4,2010-01-01 04:00:00+00:00,23.719501,67.81361,17.419500,24.480686,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,12.979984,16.622490,93.179770,94.96966,31.319998,Abbigeri